/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package VISTA;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author danie
 */
public class Internalfrm_HA extends javax.swing.JInternalFrame {

    /**
     * Creates new form Internalfrm_HA
     */
    public Internalfrm_HA() {
        initComponents();
    }

    public JButton getBtnGuardarHA() {
        return btnGuardarHA;
    }

    public JButton getBtnNuevoHosp() {
        return btnNuevoHosp;
    }

    public void setBtnNuevoHosp(JButton btnNuevoHosp) {
        this.btnNuevoHosp = btnNuevoHosp;
    }

    public void setBtnGuardarHA(JButton btnGuardarHA) {
        this.btnGuardarHA = btnGuardarHA;
    }

    public JLabel getLbl_IdAdmin_HA() {
        return lbl_IdAdmin_HA;
    }

    public void setLbl_IdAdmin_HA(JLabel lbl_IdAdmin_HA) {
        this.lbl_IdAdmin_HA = lbl_IdAdmin_HA;
    }

    public JLabel getLbl_IdHabitacion_HA() {
        return lbl_IdHabitacion_HA;
    }

    public void setLbl_IdHabitacion_HA(JLabel lbl_IdHabitacion_HA) {
        this.lbl_IdHabitacion_HA = lbl_IdHabitacion_HA;
    }

    public JComboBox<String> getTxtDisponibilidad_HA() {
        return txtDisponibilidad_HA;
    }

    public void setTxtDisponibilidad_HA(JComboBox<String> txtDisponibilidad_HA) {
        this.txtDisponibilidad_HA = txtDisponibilidad_HA;
    }

    public JTextField getTxtPrecio_HA() {
        return txtPrecio_HA;
    }

    public void setTxtPrecio_HA(JTextField txtPrecio_HA) {
        this.txtPrecio_HA = txtPrecio_HA;
    }

    public JTextField getTxtTipo_habitacion_HA() {
        return txtTipo_habitacion_HA;
    }

    public void setTxtTipo_habitacion_HA(JTextField txtTipo_habitacion_HA) {
        this.txtTipo_habitacion_HA = txtTipo_habitacion_HA;
    }

    public JButton getBtnSalir() {
        return btnSalir;
    }

    public void setBtnSalir(JButton btnSalir) {
        this.btnSalir = btnSalir;
    }

    public JLabel getLblERROR() {
        return lblERROR;
    }

    public void setLblERROR(JLabel lblERROR) {
        this.lblERROR = lblERROR;
    }

    public JLabel getLblEXITO() {
        return lblEXITO;
    }

    public void setLblEXITO(JLabel lblEXITO) {
        this.lblEXITO = lblEXITO;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jPanel37 = new javax.swing.JPanel();
        jPanel46 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jPanel38 = new javax.swing.JPanel();
        jPanel47 = new javax.swing.JPanel();
        jPanel39 = new javax.swing.JPanel();
        jPanel40 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel48 = new javax.swing.JPanel();
        jPanel41 = new javax.swing.JPanel();
        jPanel44 = new javax.swing.JPanel();
        jPanel43 = new javax.swing.JPanel();
        jPanel42 = new javax.swing.JPanel();
        jPanel45 = new javax.swing.JPanel();
        jPanel49 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbl_IdHabitacion_HA = new javax.swing.JLabel();
        btnGuardarHA = new javax.swing.JButton();
        txtPrecio_HA = new javax.swing.JTextField();
        txtTipo_habitacion_HA = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();
        lblEXITO = new javax.swing.JLabel();
        lblERROR = new javax.swing.JLabel();
        txtDisponibilidad_HA = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        lbl_IdAdmin_HA = new javax.swing.JLabel();
        btnNuevoHosp = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel26.setBackground(new java.awt.Color(0, 153, 204));

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 50, 20));

        jPanel37.setBackground(new java.awt.Color(0, 102, 204));

        javax.swing.GroupLayout jPanel37Layout = new javax.swing.GroupLayout(jPanel37);
        jPanel37.setLayout(jPanel37Layout);
        jPanel37Layout.setHorizontalGroup(
            jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel37Layout.setVerticalGroup(
            jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 50, 50));

        jPanel46.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout jPanel46Layout = new javax.swing.GroupLayout(jPanel46);
        jPanel46.setLayout(jPanel46Layout);
        jPanel46Layout.setHorizontalGroup(
            jPanel46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jPanel46Layout.setVerticalGroup(
            jPanel46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 60, -1));

        jPanel25.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 50, 40));

        jPanel38.setBackground(new java.awt.Color(0, 153, 204));

        javax.swing.GroupLayout jPanel38Layout = new javax.swing.GroupLayout(jPanel38);
        jPanel38.setLayout(jPanel38Layout);
        jPanel38Layout.setHorizontalGroup(
            jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel38Layout.setVerticalGroup(
            jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, -1, 20));

        jPanel47.setBackground(new java.awt.Color(51, 102, 255));

        javax.swing.GroupLayout jPanel47Layout = new javax.swing.GroupLayout(jPanel47);
        jPanel47.setLayout(jPanel47Layout);
        jPanel47Layout.setHorizontalGroup(
            jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel47Layout.setVerticalGroup(
            jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 50, 20));

        jPanel39.setBackground(new java.awt.Color(51, 102, 255));

        javax.swing.GroupLayout jPanel39Layout = new javax.swing.GroupLayout(jPanel39);
        jPanel39.setLayout(jPanel39Layout);
        jPanel39Layout.setHorizontalGroup(
            jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel39Layout.setVerticalGroup(
            jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, 30, 30));

        jPanel40.setBackground(new java.awt.Color(0, 153, 204));

        javax.swing.GroupLayout jPanel40Layout = new javax.swing.GroupLayout(jPanel40);
        jPanel40.setLayout(jPanel40Layout);
        jPanel40Layout.setHorizontalGroup(
            jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel40Layout.setVerticalGroup(
            jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, -1, 40));

        jLabel5.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jLabel5.setText("Disponibilidad :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jLabel3.setText("Tipo habitación :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, 20));

        jLabel4.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jLabel4.setText("Precio :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, 20));

        jPanel48.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout jPanel48Layout = new javax.swing.GroupLayout(jPanel48);
        jPanel48.setLayout(jPanel48Layout);
        jPanel48Layout.setHorizontalGroup(
            jPanel48Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jPanel48Layout.setVerticalGroup(
            jPanel48Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 60, 20));

        jPanel41.setBackground(new java.awt.Color(51, 102, 255));

        javax.swing.GroupLayout jPanel41Layout = new javax.swing.GroupLayout(jPanel41);
        jPanel41.setLayout(jPanel41Layout);
        jPanel41Layout.setHorizontalGroup(
            jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel41Layout.setVerticalGroup(
            jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 30, 40));

        jPanel44.setBackground(new java.awt.Color(0, 153, 204));

        javax.swing.GroupLayout jPanel44Layout = new javax.swing.GroupLayout(jPanel44);
        jPanel44.setLayout(jPanel44Layout);
        jPanel44Layout.setHorizontalGroup(
            jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel44Layout.setVerticalGroup(
            jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 30, 30));

        jPanel43.setBackground(new java.awt.Color(0, 102, 204));

        javax.swing.GroupLayout jPanel43Layout = new javax.swing.GroupLayout(jPanel43);
        jPanel43.setLayout(jPanel43Layout);
        jPanel43Layout.setHorizontalGroup(
            jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jPanel43Layout.setVerticalGroup(
            jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 60, 40));

        jPanel42.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout jPanel42Layout = new javax.swing.GroupLayout(jPanel42);
        jPanel42.setLayout(jPanel42Layout);
        jPanel42Layout.setHorizontalGroup(
            jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jPanel42Layout.setVerticalGroup(
            jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 60, 20));

        jPanel45.setBackground(new java.awt.Color(0, 153, 204));

        javax.swing.GroupLayout jPanel45Layout = new javax.swing.GroupLayout(jPanel45);
        jPanel45.setLayout(jPanel45Layout);
        jPanel45Layout.setHorizontalGroup(
            jPanel45Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel45Layout.setVerticalGroup(
            jPanel45Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, 50));

        jPanel49.setBackground(new java.awt.Color(0, 102, 204));

        javax.swing.GroupLayout jPanel49Layout = new javax.swing.GroupLayout(jPanel49);
        jPanel49.setLayout(jPanel49Layout);
        jPanel49Layout.setHorizontalGroup(
            jPanel49Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 66, Short.MAX_VALUE)
        );
        jPanel49Layout.setVerticalGroup(
            jPanel49Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, 30));

        jLabel2.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel2.setText("Id habitación:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 90, -1));

        lbl_IdHabitacion_HA.setFont(new java.awt.Font("Segoe UI Symbol", 2, 12)); // NOI18N
        jPanel1.add(lbl_IdHabitacion_HA, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 140, 20));

        btnGuardarHA.setBackground(new java.awt.Color(0, 204, 102));
        btnGuardarHA.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        btnGuardarHA.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarHA.setText("GUARDAR");
        btnGuardarHA.setBorder(null);
        jPanel1.add(btnGuardarHA, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 90, 30));

        txtPrecio_HA.setBackground(new java.awt.Color(235, 235, 235));
        txtPrecio_HA.setFont(new java.awt.Font("Segoe UI Symbol", 2, 12)); // NOI18N
        txtPrecio_HA.setBorder(null);
        jPanel1.add(txtPrecio_HA, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 140, 20));

        txtTipo_habitacion_HA.setBackground(new java.awt.Color(235, 235, 235));
        txtTipo_habitacion_HA.setFont(new java.awt.Font("Segoe UI Symbol", 2, 12)); // NOI18N
        txtTipo_habitacion_HA.setBorder(null);
        jPanel1.add(txtTipo_habitacion_HA, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 210, 20));

        btnSalir.setBackground(new java.awt.Color(204, 204, 255));
        btnSalir.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("<");
        btnSalir.setBorder(null);
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 20, 20));

        lblEXITO.setForeground(new java.awt.Color(0, 204, 0));
        jPanel1.add(lblEXITO, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 120, 20));

        lblERROR.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lblERROR, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 280, 20));

        txtDisponibilidad_HA.setBackground(new java.awt.Color(235, 235, 235));
        txtDisponibilidad_HA.setFont(new java.awt.Font("Segoe UI Symbol", 2, 12)); // NOI18N
        txtDisponibilidad_HA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "SI", "NO" }));
        txtDisponibilidad_HA.setBorder(null);
        txtDisponibilidad_HA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDisponibilidad_HAActionPerformed(evt);
            }
        });
        jPanel1.add(txtDisponibilidad_HA, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 70, -1));

        jLabel6.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel6.setText("Id admin:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 90, -1));

        lbl_IdAdmin_HA.setFont(new java.awt.Font("Segoe UI Symbol", 2, 12)); // NOI18N
        jPanel1.add(lbl_IdAdmin_HA, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 140, 20));

        btnNuevoHosp.setBackground(new java.awt.Color(0, 204, 255));
        btnNuevoHosp.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        btnNuevoHosp.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoHosp.setText("NUEVO");
        btnNuevoHosp.setBorder(null);
        jPanel1.add(btnNuevoHosp, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 90, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDisponibilidad_HAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDisponibilidad_HAActionPerformed
        // TODO add your handling code here
    }//GEN-LAST:event_txtDisponibilidad_HAActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarHA;
    private javax.swing.JButton btnNuevoHosp;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JPanel jPanel46;
    private javax.swing.JPanel jPanel47;
    private javax.swing.JPanel jPanel48;
    private javax.swing.JPanel jPanel49;
    private javax.swing.JLabel lblERROR;
    private javax.swing.JLabel lblEXITO;
    private javax.swing.JLabel lbl_IdAdmin_HA;
    private javax.swing.JLabel lbl_IdHabitacion_HA;
    private javax.swing.JComboBox<String> txtDisponibilidad_HA;
    private javax.swing.JTextField txtPrecio_HA;
    private javax.swing.JTextField txtTipo_habitacion_HA;
    // End of variables declaration//GEN-END:variables
}
