/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package VISTA;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author danie
 */
public class Internalfrm_Conductor extends javax.swing.JInternalFrame {

    /**
     * Creates new form Internalfrm_Conductor
     */
    public Internalfrm_Conductor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre_conductor = new javax.swing.JTextField();
        txtTelefono_conductor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        boxDia_conductor = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        boxMes_conductor = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        boxAnio_conductor = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        lbl_IdConductor = new javax.swing.JLabel();
        btnGuardarConductor = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtCedula_conductor = new javax.swing.JTextField();
        txtERROR = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtId_trans_con = new javax.swing.JTextField();
        jPanel24 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jPanel28 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        jPanel29 = new javax.swing.JPanel();
        jPanel30 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel31 = new javax.swing.JPanel();
        jPanel32 = new javax.swing.JPanel();
        jPanel33 = new javax.swing.JPanel();
        jPanel34 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel35 = new javax.swing.JPanel();
        jPanel36 = new javax.swing.JPanel();
        jPanel37 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel38 = new javax.swing.JPanel();
        btnNuevoCond = new javax.swing.JButton();
        txtEXITO = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbl_IdAdm = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 70, 29));

        txtNombre_conductor.setBackground(new java.awt.Color(235, 235, 235));
        txtNombre_conductor.setBorder(null);
        jPanel1.add(txtNombre_conductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 380, 20));

        txtTelefono_conductor.setBackground(new java.awt.Color(235, 235, 235));
        txtTelefono_conductor.setBorder(null);
        jPanel1.add(txtTelefono_conductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 380, 20));

        jLabel4.setText("Telefono :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 70, -1));

        jLabel6.setText("Fecha nacimiento");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel7.setText("Dia");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));

        boxDia_conductor.setBackground(new java.awt.Color(235, 235, 235));
        boxDia_conductor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        boxDia_conductor.setBorder(null);
        boxDia_conductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxDia_conductorActionPerformed(evt);
            }
        });
        jPanel1.add(boxDia_conductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 45, -1));

        jLabel8.setText("Mes");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, -1, -1));

        boxMes_conductor.setBackground(new java.awt.Color(235, 235, 235));
        boxMes_conductor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        boxMes_conductor.setBorder(null);
        boxMes_conductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxMes_conductorActionPerformed(evt);
            }
        });
        jPanel1.add(boxMes_conductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 100, -1));

        jLabel9.setText("Año");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, -1, -1));

        boxAnio_conductor.setBackground(new java.awt.Color(235, 235, 235));
        boxAnio_conductor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "1900", "1901", "1902", "1903", "1904", "1905", "1906", "1907", "1908", "1909", "1910", "1911", "1912", "1913", "1914", "1915", "1916", "1917", "1918", "1919", "1920", "1921", "1922", "1923", "1924", "1925", "1926", "1927", "1928", "1929", "1930", "1931", "1932", "1933", "1934", "1935", "1936", "1937", "1938", "1939", "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024" }));
        boxAnio_conductor.setBorder(null);
        jPanel1.add(boxAnio_conductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 80, -1));

        jLabel2.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel2.setText("Id conductor:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        lbl_IdConductor.setFont(new java.awt.Font("Serif", 2, 12)); // NOI18N
        jPanel1.add(lbl_IdConductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 90, 20));

        btnGuardarConductor.setBackground(new java.awt.Color(0, 204, 102));
        btnGuardarConductor.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        btnGuardarConductor.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarConductor.setText("GUARDAR");
        btnGuardarConductor.setBorder(null);
        jPanel1.add(btnGuardarConductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 110, 30));

        jLabel5.setText("Cedula :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 70, -1));

        txtCedula_conductor.setBackground(new java.awt.Color(235, 235, 235));
        txtCedula_conductor.setBorder(null);
        jPanel1.add(txtCedula_conductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 380, 20));

        txtERROR.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(txtERROR, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 260, 20));

        jLabel10.setText("Id transporte :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 82, 20));

        txtId_trans_con.setBackground(new java.awt.Color(235, 235, 235));
        txtId_trans_con.setBorder(null);
        jPanel1.add(txtId_trans_con, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 380, 20));

        jPanel24.setBackground(new java.awt.Color(102, 204, 255));

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 40, 40));

        jPanel25.setBackground(new java.awt.Color(0, 102, 204));

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 30, 30));

        jPanel28.setBackground(new java.awt.Color(51, 102, 255));

        javax.swing.GroupLayout jPanel28Layout = new javax.swing.GroupLayout(jPanel28);
        jPanel28.setLayout(jPanel28Layout);
        jPanel28Layout.setHorizontalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel28Layout.setVerticalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 50, 10));

        jPanel10.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 40, 50));

        jPanel26.setBackground(new java.awt.Color(0, 102, 204));

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, -1, 50));

        jPanel11.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, -1, 20));

        jPanel27.setBackground(new java.awt.Color(102, 204, 255));

        javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel27Layout.setVerticalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, 30, -1));

        jPanel29.setBackground(new java.awt.Color(0, 102, 204));

        javax.swing.GroupLayout jPanel29Layout = new javax.swing.GroupLayout(jPanel29);
        jPanel29.setLayout(jPanel29Layout);
        jPanel29Layout.setHorizontalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel29Layout.setVerticalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 50, 50));

        jPanel30.setBackground(new java.awt.Color(51, 102, 255));

        javax.swing.GroupLayout jPanel30Layout = new javax.swing.GroupLayout(jPanel30);
        jPanel30.setLayout(jPanel30Layout);
        jPanel30Layout.setHorizontalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel30Layout.setVerticalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, 30, 30));

        jPanel12.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, -1, -1));

        jPanel31.setBackground(new java.awt.Color(102, 204, 255));

        javax.swing.GroupLayout jPanel31Layout = new javax.swing.GroupLayout(jPanel31);
        jPanel31.setLayout(jPanel31Layout);
        jPanel31Layout.setHorizontalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jPanel31Layout.setVerticalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 60, 10));

        jPanel32.setBackground(new java.awt.Color(51, 102, 255));

        javax.swing.GroupLayout jPanel32Layout = new javax.swing.GroupLayout(jPanel32);
        jPanel32.setLayout(jPanel32Layout);
        jPanel32Layout.setHorizontalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jPanel32Layout.setVerticalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 60, 30));

        jPanel33.setBackground(new java.awt.Color(0, 102, 204));

        javax.swing.GroupLayout jPanel33Layout = new javax.swing.GroupLayout(jPanel33);
        jPanel33.setLayout(jPanel33Layout);
        jPanel33Layout.setHorizontalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel33Layout.setVerticalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 40, -1));

        jPanel34.setBackground(new java.awt.Color(51, 102, 255));

        javax.swing.GroupLayout jPanel34Layout = new javax.swing.GroupLayout(jPanel34);
        jPanel34.setLayout(jPanel34Layout);
        jPanel34Layout.setHorizontalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel34Layout.setVerticalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 40, 40));

        jPanel13.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 50, 40));

        jPanel35.setBackground(new java.awt.Color(51, 102, 255));

        javax.swing.GroupLayout jPanel35Layout = new javax.swing.GroupLayout(jPanel35);
        jPanel35.setLayout(jPanel35Layout);
        jPanel35Layout.setHorizontalGroup(
            jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel35Layout.setVerticalGroup(
            jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 40, 40));

        jPanel36.setBackground(new java.awt.Color(102, 204, 255));

        javax.swing.GroupLayout jPanel36Layout = new javax.swing.GroupLayout(jPanel36);
        jPanel36.setLayout(jPanel36Layout);
        jPanel36Layout.setHorizontalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel36Layout.setVerticalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, -1, -1));

        jPanel37.setBackground(new java.awt.Color(102, 204, 255));

        javax.swing.GroupLayout jPanel37Layout = new javax.swing.GroupLayout(jPanel37);
        jPanel37.setLayout(jPanel37Layout);
        jPanel37Layout.setHorizontalGroup(
            jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel37Layout.setVerticalGroup(
            jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, -1, -1));

        jPanel14.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 20, 40));

        jPanel38.setBackground(new java.awt.Color(102, 204, 255));

        javax.swing.GroupLayout jPanel38Layout = new javax.swing.GroupLayout(jPanel38);
        jPanel38.setLayout(jPanel38Layout);
        jPanel38Layout.setHorizontalGroup(
            jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel38Layout.setVerticalGroup(
            jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 30, 20));

        btnNuevoCond.setBackground(new java.awt.Color(0, 204, 255));
        btnNuevoCond.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        btnNuevoCond.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoCond.setText("NUEVO");
        btnNuevoCond.setBorder(null);
        jPanel1.add(btnNuevoCond, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 80, 30));

        txtEXITO.setForeground(new java.awt.Color(51, 204, 0));
        jPanel1.add(txtEXITO, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 220, 20));

        jLabel11.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel11.setText("Id admin:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 50, -1));

        lbl_IdAdm.setFont(new java.awt.Font("Serif", 2, 12)); // NOI18N
        jPanel1.add(lbl_IdAdm, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 90, 20));

        btnSalir.setBackground(new java.awt.Color(204, 204, 255));
        btnSalir.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("<");
        btnSalir.setBorder(null);
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 20, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boxDia_conductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxDia_conductorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxDia_conductorActionPerformed

    private void boxMes_conductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxMes_conductorActionPerformed
        // TODO add your handling code here
    }//GEN-LAST:event_boxMes_conductorActionPerformed

    public JTextField getTxtId_trans_con() {
        return txtId_trans_con;
    }

    public JLabel getTxtEXITO() {
        return txtEXITO;
    }

    public JButton getBtnSalir() {
        return btnSalir;
    }

    public void setBtnSalir(JButton btnSalir) {
        this.btnSalir = btnSalir;
    }

    public JLabel getLbl_IdAdm() {
        return lbl_IdAdm;
    }

    public void setLbl_IdAdm(JLabel lbl_IdAdm) {
        this.lbl_IdAdm = lbl_IdAdm;
    }

    public void setTxtEXITO(JLabel txtEXITO) {
        this.txtEXITO = txtEXITO;
    }

    public JButton getBtnNuevoCond() {
        return btnNuevoCond;
    }

    public void setBtnNuevoCond(JButton btnNuevoCond) {
        this.btnNuevoCond = btnNuevoCond;
    }
    
    public void setTxtId_trans_con(JTextField txtId_trans_con) {
        this.txtId_trans_con = txtId_trans_con;
    }

    public JComboBox<String> getBoxAnio_conductor() {
        return boxAnio_conductor;
    }

    public void setBoxAnio_conductor(JComboBox<String> boxAnio_conductor) {
        this.boxAnio_conductor = boxAnio_conductor;
    }

    public JComboBox<String> getBoxDia_conductor() {
        return boxDia_conductor;
    }

    public void setBoxDia_conductor(JComboBox<String> boxDia_conductor) {
        this.boxDia_conductor = boxDia_conductor;
    }

    public JComboBox<String> getBoxMes_conductor() {
        return boxMes_conductor;
    }

    public void setBoxMes_conductor(JComboBox<String> boxMes_conductor) {
        this.boxMes_conductor = boxMes_conductor;
    }

    public JButton getBtnGuardarConductor() {
        return btnGuardarConductor;
    }

    public void setBtnGuardarConductor(JButton btnGuardarConductor) {
        this.btnGuardarConductor = btnGuardarConductor;
    }

    public JLabel getLbl_IdConductor() {
        return lbl_IdConductor;
    }

    public void setLbl_IdConductor(JLabel lbl_IdConductor) {
        this.lbl_IdConductor = lbl_IdConductor;
    }

    public JTextField getTxtCedula_conductor() {
        return txtCedula_conductor;
    }

    public void setTxtCedula_conductor(JTextField txtCedula_conductor) {
        this.txtCedula_conductor = txtCedula_conductor;
    }

    public JLabel getTxtERROR() {
        return txtERROR;
    }

    public void setTxtERROR(JLabel txtERROR) {
        this.txtERROR = txtERROR;
    }

    public JTextField getTxtNombre_conductor() {
        return txtNombre_conductor;
    }

    public void setTxtNombre_conductor(JTextField txtNombre_conductor) {
        this.txtNombre_conductor = txtNombre_conductor;
    }

    public JTextField getTxtTelefono_conductor() {
        return txtTelefono_conductor;
    }

    public void setTxtTelefono_conductor(JTextField txtTelefono_conductor) {
        this.txtTelefono_conductor = txtTelefono_conductor;
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxAnio_conductor;
    private javax.swing.JComboBox<String> boxDia_conductor;
    private javax.swing.JComboBox<String> boxMes_conductor;
    private javax.swing.JButton btnGuardarConductor;
    private javax.swing.JButton btnNuevoCond;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JLabel lbl_IdAdm;
    private javax.swing.JLabel lbl_IdConductor;
    private javax.swing.JTextField txtCedula_conductor;
    private javax.swing.JLabel txtERROR;
    private javax.swing.JLabel txtEXITO;
    private javax.swing.JTextField txtId_trans_con;
    private javax.swing.JTextField txtNombre_conductor;
    private javax.swing.JTextField txtTelefono_conductor;
    // End of variables declaration//GEN-END:variables

    public void getLbl_IdAdm(String string) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
