/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package VISTA;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;

/**
 *
 * @author danie
 */
public class Internalfrm_Transporte extends javax.swing.JInternalFrame {

    /**
     * Creates new form Internalfrm_Transporte
     */
    public Internalfrm_Transporte() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtOrigen_transCliente = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel37 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        jPanel33 = new javax.swing.JPanel();
        jPanel34 = new javax.swing.JPanel();
        jPanel35 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblPlaca = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblIdTransporte = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        jPanel32 = new javax.swing.JPanel();
        jPanel28 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jPanel31 = new javax.swing.JPanel();
        jPanel29 = new javax.swing.JPanel();
        lblMinutos = new javax.swing.JLabel();
        lblDia = new javax.swing.JLabel();
        lblMes = new javax.swing.JLabel();
        lblAnio = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        txtDestino_transCliente = new javax.swing.JComboBox<>();
        lblPrecio_transCliente = new javax.swing.JLabel();
        lblEXITO = new javax.swing.JLabel();
        lblERROR = new javax.swing.JLabel();
        lblPrecio2 = new javax.swing.JLabel();
        lblPrecio3 = new javax.swing.JLabel();
        lblPrecio4 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnGuardar_TransCliente = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblIdTransporte_Adm = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtOrigen_transCliente.setBackground(new java.awt.Color(235, 235, 235));
        txtOrigen_transCliente.setFont(new java.awt.Font("Segoe UI Symbol", 2, 12)); // NOI18N
        txtOrigen_transCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", " " }));
        txtOrigen_transCliente.setToolTipText("");
        txtOrigen_transCliente.setBorder(null);
        txtOrigen_transCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrigen_transClienteActionPerformed(evt);
            }
        });
        jPanel1.add(txtOrigen_transCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 400, 20));

        jLabel7.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel7.setText("Fecha del transporte");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        jLabel8.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel8.setText("Hora del transporte");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, -1, -1));

        jPanel37.setBackground(new java.awt.Color(51, 102, 255));

        javax.swing.GroupLayout jPanel37Layout = new javax.swing.GroupLayout(jPanel37);
        jPanel37.setLayout(jPanel37Layout);
        jPanel37Layout.setHorizontalGroup(
            jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel37Layout.setVerticalGroup(
            jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 0, 30, 20));

        jPanel13.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 40, 30));

        jPanel27.setBackground(new java.awt.Color(0, 102, 204));

        javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jPanel27Layout.setVerticalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, -1, 20));

        jPanel33.setBackground(new java.awt.Color(51, 102, 255));

        javax.swing.GroupLayout jPanel33Layout = new javax.swing.GroupLayout(jPanel33);
        jPanel33.setLayout(jPanel33Layout);
        jPanel33Layout.setHorizontalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jPanel33Layout.setVerticalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 0, 70, 50));

        jPanel34.setBackground(new java.awt.Color(102, 204, 255));

        javax.swing.GroupLayout jPanel34Layout = new javax.swing.GroupLayout(jPanel34);
        jPanel34.setLayout(jPanel34Layout);
        jPanel34Layout.setHorizontalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel34Layout.setVerticalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, 50, -1));

        jPanel35.setBackground(new java.awt.Color(0, 102, 204));

        javax.swing.GroupLayout jPanel35Layout = new javax.swing.GroupLayout(jPanel35);
        jPanel35.setLayout(jPanel35Layout);
        jPanel35Layout.setHorizontalGroup(
            jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel35Layout.setVerticalGroup(
            jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, 30, -1));

        jPanel15.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 20, -1));

        jLabel9.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel9.setText("Origen:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jLabel10.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel10.setText("Destino:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, 20));

        jLabel4.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel4.setText("Placa:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        lblPlaca.setFont(new java.awt.Font("Serif", 2, 12)); // NOI18N
        jPanel1.add(lblPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 90, 20));

        jLabel2.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel2.setText("Id transporte:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        lblIdTransporte.setFont(new java.awt.Font("Serif", 2, 12)); // NOI18N
        jPanel1.add(lblIdTransporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 90, 20));

        jLabel11.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel11.setText("Precio:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, -1, -1));

        lblPrecio.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        lblPrecio.setText("/");
        jPanel1.add(lblPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 10, -1));

        jPanel26.setBackground(new java.awt.Color(0, 102, 204));

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 30, -1));

        jPanel32.setBackground(new java.awt.Color(102, 204, 255));

        javax.swing.GroupLayout jPanel32Layout = new javax.swing.GroupLayout(jPanel32);
        jPanel32.setLayout(jPanel32Layout);
        jPanel32Layout.setHorizontalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel32Layout.setVerticalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 40, -1));

        jPanel28.setBackground(new java.awt.Color(51, 102, 255));

        javax.swing.GroupLayout jPanel28Layout = new javax.swing.GroupLayout(jPanel28);
        jPanel28.setLayout(jPanel28Layout);
        jPanel28Layout.setHorizontalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel28Layout.setVerticalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 40, 40));

        jPanel11.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, -1, 20));

        jPanel25.setBackground(new java.awt.Color(0, 102, 204));

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 70, 40));

        jPanel31.setBackground(new java.awt.Color(102, 204, 255));

        javax.swing.GroupLayout jPanel31Layout = new javax.swing.GroupLayout(jPanel31);
        jPanel31.setLayout(jPanel31Layout);
        jPanel31Layout.setHorizontalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel31Layout.setVerticalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 50, 40));

        jPanel29.setBackground(new java.awt.Color(51, 102, 255));

        javax.swing.GroupLayout jPanel29Layout = new javax.swing.GroupLayout(jPanel29);
        jPanel29.setLayout(jPanel29Layout);
        jPanel29Layout.setHorizontalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jPanel29Layout.setVerticalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 60, -1));

        lblMinutos.setFont(new java.awt.Font("Segoe UI Symbol", 2, 12)); // NOI18N
        lblMinutos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMinutos.setText("Minutos");
        jPanel1.add(lblMinutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 60, 20));

        lblDia.setFont(new java.awt.Font("Segoe UI Symbol", 2, 12)); // NOI18N
        lblDia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDia.setText("Día");
        jPanel1.add(lblDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 60, 20));

        lblMes.setFont(new java.awt.Font("Segoe UI Symbol", 2, 12)); // NOI18N
        lblMes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMes.setText("Mes");
        jPanel1.add(lblMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 60, 20));

        lblAnio.setFont(new java.awt.Font("Segoe UI Symbol", 2, 12)); // NOI18N
        lblAnio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAnio.setText("Año");
        jPanel1.add(lblAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 60, 20));

        lblHora.setFont(new java.awt.Font("Segoe UI Symbol", 2, 12)); // NOI18N
        lblHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHora.setText("Hora");
        jPanel1.add(lblHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 60, 20));

        txtDestino_transCliente.setBackground(new java.awt.Color(235, 235, 235));
        txtDestino_transCliente.setFont(new java.awt.Font("Segoe UI Symbol", 2, 12)); // NOI18N
        txtDestino_transCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", " " }));
        txtDestino_transCliente.setBorder(null);
        txtDestino_transCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDestino_transClienteActionPerformed(evt);
            }
        });
        jPanel1.add(txtDestino_transCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 400, 20));

        lblPrecio_transCliente.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        lblPrecio_transCliente.setForeground(new java.awt.Color(0, 204, 51));
        lblPrecio_transCliente.setText("000 000");
        jPanel1.add(lblPrecio_transCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, -1, -1));

        lblEXITO.setForeground(new java.awt.Color(0, 204, 0));
        jPanel1.add(lblEXITO, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 120, 20));

        lblERROR.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lblERROR, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 280, 20));

        lblPrecio2.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        lblPrecio2.setForeground(new java.awt.Color(0, 204, 51));
        lblPrecio2.setText("$");
        jPanel1.add(lblPrecio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 10, -1));

        lblPrecio3.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        lblPrecio3.setText(":");
        jPanel1.add(lblPrecio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 10, -1));

        lblPrecio4.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        lblPrecio4.setText("/");
        jPanel1.add(lblPrecio4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 10, -1));

        btnSalir.setBackground(new java.awt.Color(204, 204, 255));
        btnSalir.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("<");
        btnSalir.setBorder(null);
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 20, 20));

        btnGuardar_TransCliente.setBackground(new java.awt.Color(0, 204, 102));
        btnGuardar_TransCliente.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        btnGuardar_TransCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar_TransCliente.setText("GUARDAR");
        btnGuardar_TransCliente.setBorder(null);
        jPanel1.add(btnGuardar_TransCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, 110, 30));

        jLabel3.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel3.setText("Id transporte admin:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 120, -1));

        lblIdTransporte_Adm.setFont(new java.awt.Font("Serif", 2, 12)); // NOI18N
        jPanel1.add(lblIdTransporte_Adm, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 100, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnSalir() {
        return btnSalir;
    }

    public void setBtnSalir(JButton btnSalir) {
        this.btnSalir = btnSalir;
    }

    private void txtDestino_transClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDestino_transClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDestino_transClienteActionPerformed

    private void txtOrigen_transClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrigen_transClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrigen_transClienteActionPerformed

    public JLabel getLblIdTransporte_Adm() {
        return lblIdTransporte_Adm;
    }

    public void setLblIdTransporte_Adm(JLabel lblIdTransporte_Adm) {
        this.lblIdTransporte_Adm = lblIdTransporte_Adm;
    }

    public JButton getBtnGuardar_TransCliente() {
        return btnGuardar_TransCliente;
    }

    public void setBtnGuardar_TransCliente(JButton btnGuardar_TransCliente) {
        this.btnGuardar_TransCliente = btnGuardar_TransCliente;
    }

    public JComboBox<String> getTxtDestino_transCliente() {
        return txtDestino_transCliente;
    }

    public void setTxtDestino_transCliente(JComboBox<String> txtDestino_transCliente) {
        this.txtDestino_transCliente = txtDestino_transCliente;
    }

    public JComboBox<String> getTxtOrigen_transCliente() {
        return txtOrigen_transCliente;
    }

    public void setTxtOrigen_transCliente(JComboBox<String> txtOrigen_transCliente) {
        this.txtOrigen_transCliente = txtOrigen_transCliente;
    }

    public JLabel getLblPrecio_transCliente() {
        return lblPrecio_transCliente;
    }

    public void setLblPrecio_transCliente(JLabel lblPrecio_transCliente) {
        this.lblPrecio_transCliente = lblPrecio_transCliente;
    }

    public JLabel getLblAnio() {
        return lblAnio;
    }

    public void setLblAnio(JLabel lblAnio) {
        this.lblAnio = lblAnio;
    }

    public JLabel getLblDia() {
        return lblDia;
    }

    public void setLblDia(JLabel lblDia) {
        this.lblDia = lblDia;
    }

    public JLabel getLblERROR() {
        return lblERROR;
    }

    public void setLblERROR(JLabel lblERROR) {
        this.lblERROR = lblERROR;
    }

    public JLabel getLblEXITO() {
        return lblEXITO;
    }

    public void setLblEXITO(JLabel lblEXITO) {
        this.lblEXITO = lblEXITO;
    }

    public JLabel getLblHora() {
        return lblHora;
    }

    public void setLblHora(JLabel lblHora) {
        this.lblHora = lblHora;
    }

    public JLabel getLblIdTransporte() {
        return lblIdTransporte;
    }

    public void setLblIdTransporte(JLabel lblIdTransporte) {
        this.lblIdTransporte = lblIdTransporte;
    }

    public JLabel getLblMes() {
        return lblMes;
    }

    public void setLblMes(JLabel lblMes) {
        this.lblMes = lblMes;
    }

    public JLabel getLblMinutos() {
        return lblMinutos;
    }

    public void setLblMinutos(JLabel lblMinutos) {
        this.lblMinutos = lblMinutos;
    }

    public JLabel getLblPlaca() {
        return lblPlaca;
    }

    public void setLblPlaca(JLabel lblPlaca) {
        this.lblPlaca = lblPlaca;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar_TransCliente;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JLabel lblAnio;
    private javax.swing.JLabel lblDia;
    private javax.swing.JLabel lblERROR;
    private javax.swing.JLabel lblEXITO;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblIdTransporte;
    private javax.swing.JLabel lblIdTransporte_Adm;
    private javax.swing.JLabel lblMes;
    private javax.swing.JLabel lblMinutos;
    private javax.swing.JLabel lblPlaca;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblPrecio2;
    private javax.swing.JLabel lblPrecio3;
    private javax.swing.JLabel lblPrecio4;
    private javax.swing.JLabel lblPrecio_transCliente;
    private javax.swing.JComboBox<String> txtDestino_transCliente;
    private javax.swing.JComboBox<String> txtOrigen_transCliente;
    // End of variables declaration//GEN-END:variables
}
