/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package VISTA;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author danie
 */
public class InternalfrmMCEtransporte extends javax.swing.JInternalFrame {

    
    public JTextField getTxt_CuposUsados_transAdm() {
        return txt_CuposUsados_transAdm;
    }

    public void setTxt_CuposUsados_transAdm(JTextField txt_CuposUsados_transAdm) {    
        this.txt_CuposUsados_transAdm = txt_CuposUsados_transAdm;
    }

    public InternalfrmMCEtransporte() {
        initComponents();
    }

    public JButton getBtnSalir() {
        return btnSalir;
    }

    public void setBtnSalir(JButton btnSalir) {
        this.btnSalir = btnSalir;
    }

    public JLabel getLblERROR() {
        return lblERROR_transAdm_Consulta;
    }

    public void setLblERROR(JLabel lblERROR) {
        this.lblERROR_transAdm_Consulta = lblERROR;
    }

    public JLabel getLblEXITO() {
        return lblEXITO_transAdm_Consulta;
    }

    public void setLblEXITO(JLabel lblEXITO) {
        this.lblEXITO_transAdm_Consulta = lblEXITO;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtOrigenConsulta_trans_adm = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtDestinoConsulta_trans_adm = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtPlacaConsultar_trans_adm = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtMesConsulta_trans_adm = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtCapacidad_trans_adm = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbl_IdAdm_transConsulta = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtId_trans_adm_Consulta = new javax.swing.JTextField();
        txtMinutosConsulta_trans_adm = new javax.swing.JTextField();
        txtDiaConsulta_trans_adm = new javax.swing.JTextField();
        txtAnioConsulta_trans_adm = new javax.swing.JTextField();
        txtHoraConsulta_trans_adm = new javax.swing.JTextField();
        btnModificar_Transporte = new javax.swing.JButton();
        btnConsultar_Transporte = new javax.swing.JButton();
        lblERROR_transAdm_Consulta = new javax.swing.JLabel();
        lblEXITO_transAdm_Consulta = new javax.swing.JLabel();
        txtValorConsultar_trans_adm = new javax.swing.JTextField();
        jPanel33 = new javax.swing.JPanel();
        jPanel34 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel31 = new javax.swing.JPanel();
        jPanel30 = new javax.swing.JPanel();
        jPanel29 = new javax.swing.JPanel();
        jPanel36 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jPanel46 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel42 = new javax.swing.JPanel();
        jPanel41 = new javax.swing.JPanel();
        jPanel43 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        jPanel44 = new javax.swing.JPanel();
        jPanel45 = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();
        jPanel35 = new javax.swing.JPanel();
        jPanel37 = new javax.swing.JPanel();
        jPanel47 = new javax.swing.JPanel();
        jPanel48 = new javax.swing.JPanel();
        jPanel49 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        btnEliminar_Transporte = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnCls = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_CuposUsados_transAdm = new javax.swing.JTextField();

        jLabel17.setText("Dia :");

        jLabel18.setText("Mes :");

        jLabel21.setText("Año :");

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtOrigenConsulta_trans_adm.setBackground(new java.awt.Color(235, 235, 235));
        txtOrigenConsulta_trans_adm.setFont(new java.awt.Font("Segoe UI Symbol", 2, 12)); // NOI18N
        txtOrigenConsulta_trans_adm.setBorder(null);
        jPanel1.add(txtOrigenConsulta_trans_adm, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 260, -1));

        jLabel9.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel9.setText("Origen:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel12.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel12.setText("Destino:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        txtDestinoConsulta_trans_adm.setBackground(new java.awt.Color(235, 235, 235));
        txtDestinoConsulta_trans_adm.setFont(new java.awt.Font("Segoe UI Symbol", 2, 12)); // NOI18N
        txtDestinoConsulta_trans_adm.setBorder(null);
        jPanel1.add(txtDestinoConsulta_trans_adm, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 260, -1));

        jLabel14.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel14.setText("Fecha transporte:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 130, -1));

        jLabel15.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel15.setText("Hora transporte:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jLabel16.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel16.setText("Placa transporte:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        txtPlacaConsultar_trans_adm.setEditable(false);
        txtPlacaConsultar_trans_adm.setBackground(new java.awt.Color(235, 235, 235));
        txtPlacaConsultar_trans_adm.setFont(new java.awt.Font("Segoe UI Symbol", 2, 12)); // NOI18N
        txtPlacaConsultar_trans_adm.setBorder(null);
        jPanel1.add(txtPlacaConsultar_trans_adm, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 130, 20));

        jLabel13.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel13.setText("Valor transporte:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, -1, -1));

        txtMesConsulta_trans_adm.setBackground(new java.awt.Color(235, 235, 235));
        txtMesConsulta_trans_adm.setFont(new java.awt.Font("Segoe UI Symbol", 2, 12)); // NOI18N
        txtMesConsulta_trans_adm.setBorder(null);
        jPanel1.add(txtMesConsulta_trans_adm, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 120, 20));

        jLabel20.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel20.setText("Capacidad de pasajeros ");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, -1, -1));

        txtCapacidad_trans_adm.setBackground(new java.awt.Color(235, 235, 235));
        txtCapacidad_trans_adm.setFont(new java.awt.Font("Segoe UI Symbol", 2, 12)); // NOI18N
        txtCapacidad_trans_adm.setBorder(null);
        txtCapacidad_trans_adm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCapacidad_trans_admActionPerformed(evt);
            }
        });
        jPanel1.add(txtCapacidad_trans_adm, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 90, 30));

        jLabel19.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel19.setText("transporte:");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, -1, -1));

        jLabel11.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText(":");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 10, -1));

        lbl_IdAdm_transConsulta.setFont(new java.awt.Font("Serif", 2, 12)); // NOI18N
        jPanel1.add(lbl_IdAdm_transConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 140, 20));

        jLabel2.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel2.setText("Id transporte admin:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, -1, -1));

        txtId_trans_adm_Consulta.setBackground(new java.awt.Color(235, 235, 235));
        txtId_trans_adm_Consulta.setFont(new java.awt.Font("Segoe UI Symbol", 2, 12)); // NOI18N
        txtId_trans_adm_Consulta.setBorder(null);
        jPanel1.add(txtId_trans_adm_Consulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 130, 20));

        txtMinutosConsulta_trans_adm.setBackground(new java.awt.Color(235, 235, 235));
        txtMinutosConsulta_trans_adm.setFont(new java.awt.Font("Segoe UI Symbol", 2, 12)); // NOI18N
        txtMinutosConsulta_trans_adm.setBorder(null);
        jPanel1.add(txtMinutosConsulta_trans_adm, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 60, 20));

        txtDiaConsulta_trans_adm.setBackground(new java.awt.Color(235, 235, 235));
        txtDiaConsulta_trans_adm.setFont(new java.awt.Font("Segoe UI Symbol", 2, 12)); // NOI18N
        txtDiaConsulta_trans_adm.setBorder(null);
        jPanel1.add(txtDiaConsulta_trans_adm, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 60, 20));

        txtAnioConsulta_trans_adm.setBackground(new java.awt.Color(235, 235, 235));
        txtAnioConsulta_trans_adm.setFont(new java.awt.Font("Segoe UI Symbol", 2, 12)); // NOI18N
        txtAnioConsulta_trans_adm.setBorder(null);
        jPanel1.add(txtAnioConsulta_trans_adm, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 60, 20));

        txtHoraConsulta_trans_adm.setBackground(new java.awt.Color(235, 235, 235));
        txtHoraConsulta_trans_adm.setFont(new java.awt.Font("Segoe UI Symbol", 2, 12)); // NOI18N
        txtHoraConsulta_trans_adm.setBorder(null);
        jPanel1.add(txtHoraConsulta_trans_adm, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 60, 20));

        btnModificar_Transporte.setBackground(new java.awt.Color(0, 204, 255));
        btnModificar_Transporte.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        btnModificar_Transporte.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar_Transporte.setText("MODIFICAR");
        btnModificar_Transporte.setBorder(null);
        btnModificar_Transporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificar_TransporteActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificar_Transporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 90, 30));

        btnConsultar_Transporte.setBackground(new java.awt.Color(0, 204, 102));
        btnConsultar_Transporte.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        btnConsultar_Transporte.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultar_Transporte.setText("CONSULTAR");
        btnConsultar_Transporte.setBorder(null);
        jPanel1.add(btnConsultar_Transporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, 90, 30));

        lblERROR_transAdm_Consulta.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lblERROR_transAdm_Consulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 280, 20));

        lblEXITO_transAdm_Consulta.setForeground(new java.awt.Color(0, 204, 0));
        jPanel1.add(lblEXITO_transAdm_Consulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 280, 20));

        txtValorConsultar_trans_adm.setBackground(new java.awt.Color(235, 235, 235));
        txtValorConsultar_trans_adm.setFont(new java.awt.Font("Segoe UI Symbol", 2, 12)); // NOI18N
        txtValorConsultar_trans_adm.setBorder(null);
        txtValorConsultar_trans_adm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorConsultar_trans_admActionPerformed(evt);
            }
        });
        jPanel1.add(txtValorConsultar_trans_adm, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 130, 20));

        jPanel33.setBackground(new java.awt.Color(51, 102, 255));

        javax.swing.GroupLayout jPanel33Layout = new javax.swing.GroupLayout(jPanel33);
        jPanel33.setLayout(jPanel33Layout);
        jPanel33Layout.setHorizontalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel33Layout.setVerticalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 20, 20));

        jPanel34.setBackground(new java.awt.Color(0, 102, 204));

        javax.swing.GroupLayout jPanel34Layout = new javax.swing.GroupLayout(jPanel34);
        jPanel34.setLayout(jPanel34Layout);
        jPanel34Layout.setHorizontalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel34Layout.setVerticalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 50, 50));

        jPanel11.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 40, 30));

        jPanel31.setBackground(new java.awt.Color(51, 102, 255));

        javax.swing.GroupLayout jPanel31Layout = new javax.swing.GroupLayout(jPanel31);
        jPanel31.setLayout(jPanel31Layout);
        jPanel31Layout.setHorizontalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel31Layout.setVerticalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 50, 40));

        jPanel30.setBackground(new java.awt.Color(102, 204, 255));

        javax.swing.GroupLayout jPanel30Layout = new javax.swing.GroupLayout(jPanel30);
        jPanel30.setLayout(jPanel30Layout);
        jPanel30Layout.setHorizontalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel30Layout.setVerticalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 40, -1));

        jPanel29.setBackground(new java.awt.Color(0, 102, 204));

        javax.swing.GroupLayout jPanel29Layout = new javax.swing.GroupLayout(jPanel29);
        jPanel29.setLayout(jPanel29Layout);
        jPanel29Layout.setHorizontalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel29Layout.setVerticalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, 30));

        jPanel36.setBackground(new java.awt.Color(51, 102, 255));

        javax.swing.GroupLayout jPanel36Layout = new javax.swing.GroupLayout(jPanel36);
        jPanel36.setLayout(jPanel36Layout);
        jPanel36Layout.setHorizontalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel36Layout.setVerticalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, 50));

        jPanel12.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, -1, 40));

        jPanel15.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 50, 20));

        jPanel24.setBackground(new java.awt.Color(102, 204, 255));

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, -1, 50));

        jPanel46.setBackground(new java.awt.Color(0, 102, 204));

        javax.swing.GroupLayout jPanel46Layout = new javax.swing.GroupLayout(jPanel46);
        jPanel46.setLayout(jPanel46Layout);
        jPanel46Layout.setHorizontalGroup(
            jPanel46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel46Layout.setVerticalGroup(
            jPanel46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 40, 40));

        jPanel10.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, -1, -1));

        jPanel42.setBackground(new java.awt.Color(51, 102, 255));

        javax.swing.GroupLayout jPanel42Layout = new javax.swing.GroupLayout(jPanel42);
        jPanel42.setLayout(jPanel42Layout);
        jPanel42Layout.setHorizontalGroup(
            jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel42Layout.setVerticalGroup(
            jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, -1, -1));

        jPanel41.setBackground(new java.awt.Color(102, 204, 255));

        javax.swing.GroupLayout jPanel41Layout = new javax.swing.GroupLayout(jPanel41);
        jPanel41.setLayout(jPanel41Layout);
        jPanel41Layout.setHorizontalGroup(
            jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel41Layout.setVerticalGroup(
            jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, -1, -1));

        jPanel43.setBackground(new java.awt.Color(0, 102, 204));

        javax.swing.GroupLayout jPanel43Layout = new javax.swing.GroupLayout(jPanel43);
        jPanel43.setLayout(jPanel43Layout);
        jPanel43Layout.setHorizontalGroup(
            jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel43Layout.setVerticalGroup(
            jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, 50, 50));

        jPanel27.setBackground(new java.awt.Color(102, 204, 255));

        javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel27Layout.setVerticalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 60, -1, -1));

        jPanel44.setBackground(new java.awt.Color(51, 102, 255));

        javax.swing.GroupLayout jPanel44Layout = new javax.swing.GroupLayout(jPanel44);
        jPanel44.setLayout(jPanel44Layout);
        jPanel44Layout.setHorizontalGroup(
            jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel44Layout.setVerticalGroup(
            jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, -1, -1));

        jPanel45.setBackground(new java.awt.Color(102, 204, 255));

        javax.swing.GroupLayout jPanel45Layout = new javax.swing.GroupLayout(jPanel45);
        jPanel45.setLayout(jPanel45Layout);
        jPanel45Layout.setHorizontalGroup(
            jPanel45Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel45Layout.setVerticalGroup(
            jPanel45Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, 20, 30));

        btnSalir.setBackground(new java.awt.Color(204, 204, 255));
        btnSalir.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("<");
        btnSalir.setBorder(null);
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 20, 20));

        jPanel35.setBackground(new java.awt.Color(0, 102, 204));

        javax.swing.GroupLayout jPanel35Layout = new javax.swing.GroupLayout(jPanel35);
        jPanel35.setLayout(jPanel35Layout);
        jPanel35Layout.setHorizontalGroup(
            jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel35Layout.setVerticalGroup(
            jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        jPanel37.setBackground(new java.awt.Color(51, 102, 255));

        javax.swing.GroupLayout jPanel37Layout = new javax.swing.GroupLayout(jPanel37);
        jPanel37.setLayout(jPanel37Layout);
        jPanel37Layout.setHorizontalGroup(
            jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel37Layout.setVerticalGroup(
            jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 50, 60));

        jPanel47.setBackground(new java.awt.Color(102, 204, 255));

        javax.swing.GroupLayout jPanel47Layout = new javax.swing.GroupLayout(jPanel47);
        jPanel47.setLayout(jPanel47Layout);
        jPanel47Layout.setHorizontalGroup(
            jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel47Layout.setVerticalGroup(
            jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, -1, -1));

        jPanel48.setBackground(new java.awt.Color(102, 204, 255));

        javax.swing.GroupLayout jPanel48Layout = new javax.swing.GroupLayout(jPanel48);
        jPanel48.setLayout(jPanel48Layout);
        jPanel48Layout.setHorizontalGroup(
            jPanel48Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel48Layout.setVerticalGroup(
            jPanel48Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, -1, -1));

        jPanel49.setBackground(new java.awt.Color(102, 204, 255));

        javax.swing.GroupLayout jPanel49Layout = new javax.swing.GroupLayout(jPanel49);
        jPanel49.setLayout(jPanel49Layout);
        jPanel49Layout.setHorizontalGroup(
            jPanel49Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel49Layout.setVerticalGroup(
            jPanel49Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 40, 40));

        jPanel13.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, -1));

        jPanel14.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 30, -1));

        btnEliminar_Transporte.setBackground(new java.awt.Color(255, 0, 0));
        btnEliminar_Transporte.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        btnEliminar_Transporte.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar_Transporte.setText("ELIMINAR");
        btnEliminar_Transporte.setBorder(null);
        jPanel1.add(btnEliminar_Transporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 80, 30));

        jLabel7.setText("Dia :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel8.setText("Mes :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        jLabel10.setText(":");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 0, -1));

        btnCls.setBackground(new java.awt.Color(204, 204, 255));
        btnCls.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        btnCls.setForeground(new java.awt.Color(255, 255, 255));
        btnCls.setText("CLS");
        btnCls.setBorder(null);
        jPanel1.add(btnCls, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 30, 20));

        jLabel24.setText("Año :");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, -1, -1));

        jLabel25.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel25.setText("Id admin:");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 70, -1));

        jLabel3.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel3.setText("Cupos usados:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, -1, -1));

        txt_CuposUsados_transAdm.setBackground(new java.awt.Color(235, 235, 235));
        txt_CuposUsados_transAdm.setFont(new java.awt.Font("Segoe UI Symbol", 2, 12)); // NOI18N
        txt_CuposUsados_transAdm.setBorder(null);
        jPanel1.add(txt_CuposUsados_transAdm, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 130, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCapacidad_trans_admActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCapacidad_trans_admActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCapacidad_trans_admActionPerformed

    private void txtValorConsultar_trans_admActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorConsultar_trans_admActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorConsultar_trans_admActionPerformed

    private void btnModificar_TransporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificar_TransporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificar_TransporteActionPerformed

    public JButton getBtnConsultar_Transporte() {
        return btnConsultar_Transporte;
    }

    public void setBtnConsultar_Transporte(JButton btnConsultar_Transporte) {
        this.btnConsultar_Transporte = btnConsultar_Transporte;
    }

    public JButton getBtnEliminar_Transporte() {
        return btnEliminar_Transporte;
    }

    public void setBtnEliminar_Transporte(JButton btnEliminar_Transporte) {
        this.btnEliminar_Transporte = btnEliminar_Transporte;
    }

    public JButton getBtnModificar_Transporte() {
        return btnModificar_Transporte;
    }

    public void setBtnModificar_Transporte(JButton btnModificar_Transporte) {
        this.btnModificar_Transporte = btnModificar_Transporte;
    }

    public JLabel getLblERROR_transAdm_Consulta() {
        return lblERROR_transAdm_Consulta;
    }

    public void setLblERROR_transAdm_Consulta(JLabel lblERROR_transAdm_Consulta) {
        this.lblERROR_transAdm_Consulta = lblERROR_transAdm_Consulta;
    }

    public JLabel getLblEXITO_transAdm_Consulta() {
        return lblEXITO_transAdm_Consulta;
    }

    public JButton getBtnCls() {
        return btnCls;
    }

    public void setBtnCls(JButton btnCls) {
        this.btnCls = btnCls;
    }

    public void setLblEXITO_transAdm_Consulta(JLabel lblEXITO_transAdm_Consulta) {
        this.lblEXITO_transAdm_Consulta = lblEXITO_transAdm_Consulta;
    }

    public JLabel getLbl_IdAdm_transConsulta() {
        return lbl_IdAdm_transConsulta;
    }

    public void setLbl_IdAdm_transConsulta(JLabel lbl_IdAdm_transConsulta) {
        this.lbl_IdAdm_transConsulta = lbl_IdAdm_transConsulta;
    }

    public JTextField getTxtAnioConsulta_trans_adm() {
        return txtAnioConsulta_trans_adm;
    }

    public void setTxtAnioConsulta_trans_adm(JTextField txtAnioConsulta_trans_adm) {
        this.txtAnioConsulta_trans_adm = txtAnioConsulta_trans_adm;
    }

    public JTextField getTxtCapacidad_trans_adm() {
        return txtCapacidad_trans_adm;
    }

    public void setTxtCapacidad_trans_adm(JTextField txtCapacidad_trans_adm) {
        this.txtCapacidad_trans_adm = txtCapacidad_trans_adm;
    }

    public JTextField getTxtDestinoConsulta_trans_adm() {
        return txtDestinoConsulta_trans_adm;
    }

    public void setTxtDestinoConsulta_trans_adm(JTextField txtDestinoConsulta_trans_adm) {
        this.txtDestinoConsulta_trans_adm = txtDestinoConsulta_trans_adm;
    }

    public JTextField getTxtDiaConsulta_trans_adm() {
        return txtDiaConsulta_trans_adm;
    }

    public void setTxtDiaConsulta_trans_adm(JTextField txtDiaConsulta_trans_adm) {
        this.txtDiaConsulta_trans_adm = txtDiaConsulta_trans_adm;
    }

    public JTextField getTxtHoraConsulta_trans_adm() {
        return txtHoraConsulta_trans_adm;
    }

    public void setTxtHoraConsulta_trans_adm(JTextField txtHoraConsulta_trans_adm) {
        this.txtHoraConsulta_trans_adm = txtHoraConsulta_trans_adm;
    }

    public JTextField getTxtId_trans_adm_Consulta() {
        return txtId_trans_adm_Consulta;
    }

    public void setTxtId_trans_adm_Consulta(JTextField txtId_trans_adm_Consulta) {
        this.txtId_trans_adm_Consulta = txtId_trans_adm_Consulta;
    }

    public JTextField getTxtMesConsulta_trans_adm() {
        return txtMesConsulta_trans_adm;
    }

    public void setTxtMesConsulta_trans_adm(JTextField txtMesConsulta_trans_adm) {
        this.txtMesConsulta_trans_adm = txtMesConsulta_trans_adm;
    }

    public JTextField getTxtMinutosConsulta_trans_adm() {
        return txtMinutosConsulta_trans_adm;
    }

    public void setTxtMinutosConsulta_trans_adm(JTextField txtMinutosConsulta_trans_adm) {
        this.txtMinutosConsulta_trans_adm = txtMinutosConsulta_trans_adm;
    }

    public JTextField getTxtOrigenConsulta_trans_adm() {
        return txtOrigenConsulta_trans_adm;
    }

    public void setTxtOrigenConsulta_trans_adm(JTextField txtOrigenConsulta_trans_adm) {
        this.txtOrigenConsulta_trans_adm = txtOrigenConsulta_trans_adm;
    }

    public JTextField getTxtPlacaConsultar_trans_adm() {
        return txtPlacaConsultar_trans_adm;
    }

    public void setTxtPlacaConsultar_trans_adm(JTextField txtPlacaConsultar_trans_adm) {
        this.txtPlacaConsultar_trans_adm = txtPlacaConsultar_trans_adm;
    }

    public JTextField getTxtValorConsultar_trans_adm() {
        return txtValorConsultar_trans_adm;
    }

    public void setTxtValorConsultar_trans_adm(JTextField txtValorConsultar_trans_adm) {
        this.txtValorConsultar_trans_adm = txtValorConsultar_trans_adm;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCls;
    private javax.swing.JButton btnConsultar_Transporte;
    private javax.swing.JButton btnEliminar_Transporte;
    private javax.swing.JButton btnModificar_Transporte;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JPanel jPanel46;
    private javax.swing.JPanel jPanel47;
    private javax.swing.JPanel jPanel48;
    private javax.swing.JPanel jPanel49;
    private javax.swing.JLabel lblERROR_transAdm_Consulta;
    private javax.swing.JLabel lblEXITO_transAdm_Consulta;
    private javax.swing.JLabel lbl_IdAdm_transConsulta;
    private javax.swing.JTextField txtAnioConsulta_trans_adm;
    private javax.swing.JTextField txtCapacidad_trans_adm;
    private javax.swing.JTextField txtDestinoConsulta_trans_adm;
    private javax.swing.JTextField txtDiaConsulta_trans_adm;
    private javax.swing.JTextField txtHoraConsulta_trans_adm;
    private javax.swing.JTextField txtId_trans_adm_Consulta;
    private javax.swing.JTextField txtMesConsulta_trans_adm;
    private javax.swing.JTextField txtMinutosConsulta_trans_adm;
    private javax.swing.JTextField txtOrigenConsulta_trans_adm;
    private javax.swing.JTextField txtPlacaConsultar_trans_adm;
    private javax.swing.JTextField txtValorConsultar_trans_adm;
    private javax.swing.JTextField txt_CuposUsados_transAdm;
    // End of variables declaration//GEN-END:variables
}
