/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package VISTA;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author danie
 */
public class Internalfrm_EspacioServicio extends javax.swing.JInternalFrame {

    /**
     * Creates new form Internalfrm_EspacioServicio
     */
    public Internalfrm_EspacioServicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtPrecioEspacio = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtDireccion_espacio = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtPropietario_espacio = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        lblIdEspacio = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblIdAdmin = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        btnNuevoEspacioServ = new javax.swing.JButton();
        btnGuardar_EspacioServ = new javax.swing.JButton();
        txtEXITO = new javax.swing.JLabel();
        txtERROR = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPrecioEspacio.setBackground(new java.awt.Color(235, 235, 235));
        txtPrecioEspacio.setFont(new java.awt.Font("Segoe UI Symbol", 2, 12)); // NOI18N
        txtPrecioEspacio.setActionCommand("<Not Set>");
        txtPrecioEspacio.setBorder(null);
        txtPrecioEspacio.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtPrecioEspacio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioEspacioActionPerformed(evt);
            }
        });
        jPanel1.add(txtPrecioEspacio, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 190, 20));

        jLabel10.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jLabel10.setText("Precio :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 80, 20));

        jLabel12.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jLabel12.setText("Direccion :");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, 20));

        txtDireccion_espacio.setBackground(new java.awt.Color(235, 235, 235));
        txtDireccion_espacio.setFont(new java.awt.Font("Segoe UI Symbol", 2, 12)); // NOI18N
        txtDireccion_espacio.setActionCommand("<Not Set>");
        txtDireccion_espacio.setBorder(null);
        txtDireccion_espacio.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtDireccion_espacio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccion_espacioActionPerformed(evt);
            }
        });
        jPanel1.add(txtDireccion_espacio, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 190, 20));

        jLabel14.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jLabel14.setText("Propietario :");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, 20));

        txtPropietario_espacio.setBackground(new java.awt.Color(235, 235, 235));
        txtPropietario_espacio.setFont(new java.awt.Font("Segoe UI Symbol", 2, 12)); // NOI18N
        txtPropietario_espacio.setActionCommand("<Not Set>");
        txtPropietario_espacio.setBorder(null);
        txtPropietario_espacio.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtPropietario_espacio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPropietario_espacioActionPerformed(evt);
            }
        });
        jPanel1.add(txtPropietario_espacio, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 190, 20));

        jLabel7.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel7.setText("Id espacio:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, 20));

        lblIdEspacio.setFont(new java.awt.Font("Serif", 2, 12)); // NOI18N
        jPanel1.add(lblIdEspacio, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 100, 20));

        jLabel6.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel6.setText("Id admin:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, 20));

        lblIdAdmin.setFont(new java.awt.Font("Serif", 2, 12)); // NOI18N
        jPanel1.add(lblIdAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 100, 20));

        jPanel8.setBackground(new java.awt.Color(51, 102, 255));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 30, 40));

        jPanel9.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, 50));

        jPanel11.setBackground(new java.awt.Color(51, 102, 255));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 50, 20));

        jPanel12.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        jPanel13.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 20, 20));

        btnSalir.setBackground(new java.awt.Color(204, 204, 255));
        btnSalir.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("<");
        btnSalir.setBorder(null);
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 20, 20));

        jPanel3.setBackground(new java.awt.Color(51, 102, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 70, -1));

        jPanel6.setBackground(new java.awt.Color(0, 153, 204));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 30, 20));

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 40, 30));

        jPanel16.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 30, 20));

        jPanel4.setBackground(new java.awt.Color(0, 153, 204));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 30, 40));

        jPanel5.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 20, -1));

        jPanel17.setBackground(new java.awt.Color(51, 102, 255));

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, 40, 50));

        btnNuevoEspacioServ.setBackground(new java.awt.Color(0, 204, 255));
        btnNuevoEspacioServ.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        btnNuevoEspacioServ.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoEspacioServ.setText("NUEVO");
        btnNuevoEspacioServ.setBorder(null);
        jPanel1.add(btnNuevoEspacioServ, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 80, 30));

        btnGuardar_EspacioServ.setBackground(new java.awt.Color(0, 204, 102));
        btnGuardar_EspacioServ.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        btnGuardar_EspacioServ.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar_EspacioServ.setText("GUARDAR");
        btnGuardar_EspacioServ.setBorder(null);
        jPanel1.add(btnGuardar_EspacioServ, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 110, 30));

        txtEXITO.setForeground(new java.awt.Color(51, 204, 0));
        jPanel1.add(txtEXITO, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 170, 20));

        txtERROR.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(txtERROR, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 210, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPrecioEspacioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioEspacioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioEspacioActionPerformed

    private void txtDireccion_espacioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccion_espacioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccion_espacioActionPerformed

    private void txtPropietario_espacioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPropietario_espacioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPropietario_espacioActionPerformed

    public JButton getBtnGuardar_EspacioServ() {
        return btnGuardar_EspacioServ;
    }

    public JTextField getTxtDireccion_espacio() {
        return txtDireccion_espacio;
    }

    public void setTxtDireccion_espacio(JTextField txtDireccion_espacio) {
        this.txtDireccion_espacio = txtDireccion_espacio;
    }

    public void setBtnGuardar_EspacioServ(JButton btnGuardar_EspacioServ) {
        this.btnGuardar_EspacioServ = btnGuardar_EspacioServ;
    }

    public JButton getBtnNuevoEspacioServ() {
        return btnNuevoEspacioServ;
    }

    public void setBtnNuevoEspacioServ(JButton btnNuevoEspacioServ) {
        this.btnNuevoEspacioServ = btnNuevoEspacioServ;
    }

    public JButton getBtnSalir() {
        return btnSalir;
    }

    public void setBtnSalir(JButton btnSalir) {
        this.btnSalir = btnSalir;
    }

    public JLabel getLblIdAdmin() {
        return lblIdAdmin;
    }

    public void setLblIdAdmin(JLabel lblIdAdmin) {
        this.lblIdAdmin = lblIdAdmin;
    }

    public JLabel getLblIdEspacio() {
        return lblIdEspacio;
    }

    public void setLblIdEspacio(JLabel lblIdEspacio) {
        this.lblIdEspacio = lblIdEspacio;
    }

    public JLabel getTxtERROR() {
        return txtERROR;
    }

    public void setTxtERROR(JLabel txtERROR) {
        this.txtERROR = txtERROR;
    }

    public JLabel getTxtEXITO() {
        return txtEXITO;
    }

    public void setTxtEXITO(JLabel txtEXITO) {
        this.txtEXITO = txtEXITO;
    }

    public JTextField getTxtPrecioEspacio() {
        return txtPrecioEspacio;
    }

    public void setTxtPrecioEspacio(JTextField txtPrecioEspacio) {
        this.txtPrecioEspacio = txtPrecioEspacio;
    }

    public JTextField getTxtPropietario_espacio() {
        return txtPropietario_espacio;
    }

    public void setTxtPropietario_espacio(JTextField txtPropietario_espacio) {
        this.txtPropietario_espacio = txtPropietario_espacio;
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar_EspacioServ;
    private javax.swing.JButton btnNuevoEspacioServ;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblIdAdmin;
    private javax.swing.JLabel lblIdEspacio;
    private javax.swing.JTextField txtDireccion_espacio;
    private javax.swing.JLabel txtERROR;
    private javax.swing.JLabel txtEXITO;
    private javax.swing.JTextField txtPrecioEspacio;
    private javax.swing.JTextField txtPropietario_espacio;
    // End of variables declaration//GEN-END:variables
}
