/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package VISTA;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author danie
 */
public class InternalfrmMCEservicio extends javax.swing.JInternalFrame {

    /**
     * Creates new form InternalfrmMCEservicio
     */
    public InternalfrmMCEservicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtNomSerConsulta = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtMinutosINSer_Consulta = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCuposUsoConsultar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtPrecioServConsulta = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnModificar_SerAdm = new javax.swing.JButton();
        btnEliminarSer_Adm = new javax.swing.JButton();
        btnConsultarSer_Adm = new javax.swing.JButton();
        txtCuposDisConsultar = new javax.swing.JTextField();
        txtHoraINSer_Consulta = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        lbl_IdAdm = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtIdSer_Consulta = new javax.swing.JTextField();
        lblERROR = new javax.swing.JLabel();
        lblEXITO = new javax.swing.JLabel();
        jPanel27 = new javax.swing.JPanel();
        jPanel43 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jPanel46 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel28 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jPanel44 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel29 = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();
        txtHoraFINSer_Consulta = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtMinutosFINSer_Consulta = new javax.swing.JTextField();
        btnCls = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lbl_IdEspacio = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jLabel3.setText("Nombre servicio :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        txtNomSerConsulta.setBackground(new java.awt.Color(235, 235, 235));
        txtNomSerConsulta.setFont(new java.awt.Font("Segoe UI Symbol", 2, 12)); // NOI18N
        txtNomSerConsulta.setActionCommand("<Not Set>");
        txtNomSerConsulta.setBorder(null);
        txtNomSerConsulta.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNomSerConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomSerConsultaActionPerformed(evt);
            }
        });
        jPanel1.add(txtNomSerConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 190, 20));

        jLabel4.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jLabel4.setText("Cupos disponibles :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        txtMinutosINSer_Consulta.setBackground(new java.awt.Color(235, 235, 235));
        txtMinutosINSer_Consulta.setFont(new java.awt.Font("Segoe UI Symbol", 2, 12)); // NOI18N
        txtMinutosINSer_Consulta.setActionCommand("<Not Set>");
        txtMinutosINSer_Consulta.setBorder(null);
        txtMinutosINSer_Consulta.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtMinutosINSer_Consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMinutosINSer_ConsultaActionPerformed(evt);
            }
        });
        jPanel1.add(txtMinutosINSer_Consulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 60, 20));

        jLabel5.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jLabel5.setText("Cupos en uso :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        txtCuposUsoConsultar.setBackground(new java.awt.Color(235, 235, 235));
        txtCuposUsoConsultar.setFont(new java.awt.Font("Segoe UI Symbol", 2, 12)); // NOI18N
        txtCuposUsoConsultar.setActionCommand("<Not Set>");
        txtCuposUsoConsultar.setBorder(null);
        txtCuposUsoConsultar.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtCuposUsoConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCuposUsoConsultarActionPerformed(evt);
            }
        });
        jPanel1.add(txtCuposUsoConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 90, 20));

        jLabel8.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jLabel8.setText("Precio :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        txtPrecioServConsulta.setBackground(new java.awt.Color(235, 235, 235));
        txtPrecioServConsulta.setFont(new java.awt.Font("Segoe UI Symbol", 2, 12)); // NOI18N
        txtPrecioServConsulta.setActionCommand("<Not Set>");
        txtPrecioServConsulta.setBorder(null);
        txtPrecioServConsulta.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtPrecioServConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioServConsultaActionPerformed(evt);
            }
        });
        jPanel1.add(txtPrecioServConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 140, 20));

        jLabel9.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Hora inicio servicio");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 120, -1));

        btnModificar_SerAdm.setBackground(new java.awt.Color(0, 204, 255));
        btnModificar_SerAdm.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        btnModificar_SerAdm.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar_SerAdm.setText("MODIFICAR");
        btnModificar_SerAdm.setBorder(null);
        jPanel1.add(btnModificar_SerAdm, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 80, 30));

        btnEliminarSer_Adm.setBackground(new java.awt.Color(255, 0, 0));
        btnEliminarSer_Adm.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        btnEliminarSer_Adm.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarSer_Adm.setText("ELIMINAR");
        btnEliminarSer_Adm.setBorder(null);
        jPanel1.add(btnEliminarSer_Adm, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 80, 30));

        btnConsultarSer_Adm.setBackground(new java.awt.Color(0, 204, 102));
        btnConsultarSer_Adm.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        btnConsultarSer_Adm.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultarSer_Adm.setText("CONSULTAR");
        btnConsultarSer_Adm.setBorder(null);
        jPanel1.add(btnConsultarSer_Adm, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 80, 30));

        txtCuposDisConsultar.setBackground(new java.awt.Color(235, 235, 235));
        txtCuposDisConsultar.setFont(new java.awt.Font("Segoe UI Symbol", 2, 12)); // NOI18N
        txtCuposDisConsultar.setActionCommand("<Not Set>");
        txtCuposDisConsultar.setBorder(null);
        txtCuposDisConsultar.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtCuposDisConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCuposDisConsultarActionPerformed(evt);
            }
        });
        jPanel1.add(txtCuposDisConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 90, 20));

        txtHoraINSer_Consulta.setBackground(new java.awt.Color(235, 235, 235));
        txtHoraINSer_Consulta.setFont(new java.awt.Font("Segoe UI Symbol", 2, 12)); // NOI18N
        txtHoraINSer_Consulta.setActionCommand("<Not Set>");
        txtHoraINSer_Consulta.setBorder(null);
        txtHoraINSer_Consulta.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtHoraINSer_Consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoraINSer_ConsultaActionPerformed(evt);
            }
        });
        jPanel1.add(txtHoraINSer_Consulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 60, 20));

        jLabel11.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel11.setText(":");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 50, 0, -1));

        lbl_IdAdm.setFont(new java.awt.Font("Serif", 2, 12)); // NOI18N
        jPanel1.add(lbl_IdAdm, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 90, 20));

        jLabel12.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jLabel12.setText("Id servicio :");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        txtIdSer_Consulta.setBackground(new java.awt.Color(235, 235, 235));
        txtIdSer_Consulta.setFont(new java.awt.Font("Segoe UI Symbol", 2, 12)); // NOI18N
        txtIdSer_Consulta.setActionCommand("<Not Set>");
        txtIdSer_Consulta.setBorder(null);
        txtIdSer_Consulta.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtIdSer_Consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdSer_ConsultaActionPerformed(evt);
            }
        });
        jPanel1.add(txtIdSer_Consulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 140, 20));

        lblERROR.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lblERROR, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 260, 20));

        lblEXITO.setForeground(new java.awt.Color(0, 204, 0));
        jPanel1.add(lblEXITO, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 260, 20));

        jPanel27.setBackground(new java.awt.Color(102, 204, 255));

        javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel27Layout.setVerticalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, -1, 60));

        jPanel43.setBackground(new java.awt.Color(0, 102, 204));

        javax.swing.GroupLayout jPanel43Layout = new javax.swing.GroupLayout(jPanel43);
        jPanel43.setLayout(jPanel43Layout);
        jPanel43Layout.setHorizontalGroup(
            jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel43Layout.setVerticalGroup(
            jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 40, 40));

        jPanel10.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, -1, 70));

        jPanel24.setBackground(new java.awt.Color(102, 204, 255));

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, -1, -1));

        jPanel26.setBackground(new java.awt.Color(0, 102, 204));

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, -1, -1));

        jPanel46.setBackground(new java.awt.Color(0, 102, 204));

        javax.swing.GroupLayout jPanel46Layout = new javax.swing.GroupLayout(jPanel46);
        jPanel46.setLayout(jPanel46Layout);
        jPanel46Layout.setHorizontalGroup(
            jPanel46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel46Layout.setVerticalGroup(
            jPanel46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, -1, -1));

        jPanel11.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, -1, 30));

        jPanel28.setBackground(new java.awt.Color(0, 102, 204));

        javax.swing.GroupLayout jPanel28Layout = new javax.swing.GroupLayout(jPanel28);
        jPanel28.setLayout(jPanel28Layout);
        jPanel28Layout.setHorizontalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel28Layout.setVerticalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, -1, -1));

        jPanel12.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, -1, -1));

        jPanel25.setBackground(new java.awt.Color(102, 204, 255));

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, 50));

        jPanel44.setBackground(new java.awt.Color(0, 102, 204));

        javax.swing.GroupLayout jPanel44Layout = new javax.swing.GroupLayout(jPanel44);
        jPanel44.setLayout(jPanel44Layout);
        jPanel44Layout.setHorizontalGroup(
            jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel44Layout.setVerticalGroup(
            jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, 30));

        jPanel13.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 50, 40));

        jPanel29.setBackground(new java.awt.Color(0, 102, 204));

        javax.swing.GroupLayout jPanel29Layout = new javax.swing.GroupLayout(jPanel29);
        jPanel29.setLayout(jPanel29Layout);
        jPanel29Layout.setHorizontalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel29Layout.setVerticalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        btnSalir.setBackground(new java.awt.Color(204, 204, 255));
        btnSalir.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("<");
        btnSalir.setBorder(null);
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 20, 20));

        txtHoraFINSer_Consulta.setBackground(new java.awt.Color(235, 235, 235));
        txtHoraFINSer_Consulta.setFont(new java.awt.Font("Segoe UI Symbol", 2, 12)); // NOI18N
        txtHoraFINSer_Consulta.setActionCommand("<Not Set>");
        txtHoraFINSer_Consulta.setBorder(null);
        txtHoraFINSer_Consulta.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtHoraFINSer_Consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoraFINSer_ConsultaActionPerformed(evt);
            }
        });
        jPanel1.add(txtHoraFINSer_Consulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 60, 20));

        jLabel13.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Hora fin servicio");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 120, -1));

        txtMinutosFINSer_Consulta.setBackground(new java.awt.Color(235, 235, 235));
        txtMinutosFINSer_Consulta.setFont(new java.awt.Font("Segoe UI Symbol", 2, 12)); // NOI18N
        txtMinutosFINSer_Consulta.setActionCommand("<Not Set>");
        txtMinutosFINSer_Consulta.setBorder(null);
        txtMinutosFINSer_Consulta.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtMinutosFINSer_Consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMinutosFINSer_ConsultaActionPerformed(evt);
            }
        });
        jPanel1.add(txtMinutosFINSer_Consulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 60, 20));

        btnCls.setBackground(new java.awt.Color(204, 204, 255));
        btnCls.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        btnCls.setForeground(new java.awt.Color(255, 255, 255));
        btnCls.setText("CLS");
        btnCls.setBorder(null);
        jPanel1.add(btnCls, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 30, 20));

        jLabel14.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel14.setText("Id admin:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 50, -1));

        jLabel15.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel15.setText(":");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 10, -1));

        jLabel16.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel16.setText(":");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 10, -1));

        jLabel17.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel17.setText("Id espacio servicio:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 110, -1));

        lbl_IdEspacio.setFont(new java.awt.Font("Serif", 2, 12)); // NOI18N
        jPanel1.add(lbl_IdEspacio, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 90, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnSalir() {
        return btnSalir;
    }

    public void setBtnSalir(JButton btnSalir) {
        this.btnSalir = btnSalir;
    }

    private void txtNomSerConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomSerConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomSerConsultaActionPerformed

    private void txtMinutosINSer_ConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMinutosINSer_ConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMinutosINSer_ConsultaActionPerformed

    private void txtCuposUsoConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCuposUsoConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCuposUsoConsultarActionPerformed

    private void txtPrecioServConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioServConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioServConsultaActionPerformed

    private void txtCuposDisConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCuposDisConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCuposDisConsultarActionPerformed

    private void txtHoraINSer_ConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoraINSer_ConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoraINSer_ConsultaActionPerformed

    private void txtIdSer_ConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdSer_ConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdSer_ConsultaActionPerformed

    private void txtHoraFINSer_ConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoraFINSer_ConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoraFINSer_ConsultaActionPerformed

    private void txtMinutosFINSer_ConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMinutosFINSer_ConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMinutosFINSer_ConsultaActionPerformed

    public JButton getBtnConsultarSer_Adm() {
        return btnConsultarSer_Adm;
    }

    public JLabel getLbl_IdEspacio() {
        return lbl_IdEspacio;
    }

    public void setLbl_IdEspacio(JLabel lbl_IdEspacio) {
        this.lbl_IdEspacio = lbl_IdEspacio;
    }

    public JButton getBtnCls() {
        return btnCls;
    }

    public void setBtnCls(JButton btnCls) {
        this.btnCls = btnCls;
    }
    
    public void setBtnConsultarSer_Adm(JButton btnConsultarSer_Adm) {
        this.btnConsultarSer_Adm = btnConsultarSer_Adm;
    }

    public JButton getBtnEliminarSer_Adm() {
        return btnEliminarSer_Adm;
    }

    public void setBtnEliminarSer_Adm(JButton btnEliminarSer_Adm) {
        this.btnEliminarSer_Adm = btnEliminarSer_Adm;
    }

    public JButton getBtnModificar_SerAdm() {
        return btnModificar_SerAdm;
    }

    public void setBtnModificar_SerAdm(JButton btnModificar_SerAdm) {
        this.btnModificar_SerAdm = btnModificar_SerAdm;
    }

    public JLabel getLblERROR() {
        return lblERROR;
    }

    public void setLblERROR(JLabel lblERROR) {
        this.lblERROR = lblERROR;
    }

    public JLabel getLblEXITO() {
        return lblEXITO;
    }

    public void setLblEXITO(JLabel lblEXITO) {
        this.lblEXITO = lblEXITO;
    }

    public JLabel getLbl_IdAdm() {
        return lbl_IdAdm;
    }

    public void setLbl_IdAdm(JLabel lbl_IdAdm) {
        this.lbl_IdAdm = lbl_IdAdm;
    }

    public JTextField getTxtCuposDisConsultar() {
        return txtCuposDisConsultar;
    }

    public void setTxtCuposDisConsultar(JTextField txtCuposDisConsultar) {
        this.txtCuposDisConsultar = txtCuposDisConsultar;
    }

    public JTextField getTxtCuposUsoConsultar() {
        return txtCuposUsoConsultar;
    }

    public void setTxtCuposUsoConsultar(JTextField txtCuposUsoConsultar) {
        this.txtCuposUsoConsultar = txtCuposUsoConsultar;
    }

    public JTextField getTxtHoraFINSer_Consulta() {
        return txtHoraFINSer_Consulta;
    }

    public void setTxtHoraFINSer_Consulta(JTextField txtHoraFINSer_Consulta) {
        this.txtHoraFINSer_Consulta = txtHoraFINSer_Consulta;
    }

    public JTextField getTxtHoraINSer_Consulta() {
        return txtHoraINSer_Consulta;
    }

    public void setTxtHoraINSer_Consulta(JTextField txtHoraINSer_Consulta) {
        this.txtHoraINSer_Consulta = txtHoraINSer_Consulta;
    }

    public JTextField getTxtIdSer_Consulta() {
        return txtIdSer_Consulta;
    }

    public void setTxtIdSer_Consulta(JTextField txtIdSer_Consulta) {
        this.txtIdSer_Consulta = txtIdSer_Consulta;
    }

    public JTextField getTxtMinutosFINSer_Consulta() {
        return txtMinutosFINSer_Consulta;
    }

    public void setTxtMinutosFINSer_Consulta(JTextField txtMinutosFINSer_Consulta) {
        this.txtMinutosFINSer_Consulta = txtMinutosFINSer_Consulta;
    }

    public JTextField getTxtMinutosINSer_Consulta() {
        return txtMinutosINSer_Consulta;
    }

    public void setTxtMinutosINSer_Consulta(JTextField txtMinutosINSer_Consulta) {
        this.txtMinutosINSer_Consulta = txtMinutosINSer_Consulta;
    }

    public JTextField getTxtNomSerConsulta() {
        return txtNomSerConsulta;
    }

    public void setTxtNomSerConsulta(JTextField txtNomSerConsulta) {
        this.txtNomSerConsulta = txtNomSerConsulta;
    }

    public JTextField getTxtPrecioServConsulta() {
        return txtPrecioServConsulta;
    }

    public void setTxtPrecioServConsulta(JTextField txtPrecioServConsulta) {
        this.txtPrecioServConsulta = txtPrecioServConsulta;
    }

    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCls;
    private javax.swing.JButton btnConsultarSer_Adm;
    private javax.swing.JButton btnEliminarSer_Adm;
    private javax.swing.JButton btnModificar_SerAdm;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel46;
    private javax.swing.JLabel lblERROR;
    private javax.swing.JLabel lblEXITO;
    private javax.swing.JLabel lbl_IdAdm;
    private javax.swing.JLabel lbl_IdEspacio;
    private javax.swing.JTextField txtCuposDisConsultar;
    private javax.swing.JTextField txtCuposUsoConsultar;
    private javax.swing.JTextField txtHoraFINSer_Consulta;
    private javax.swing.JTextField txtHoraINSer_Consulta;
    private javax.swing.JTextField txtIdSer_Consulta;
    private javax.swing.JTextField txtMinutosFINSer_Consulta;
    private javax.swing.JTextField txtMinutosINSer_Consulta;
    private javax.swing.JTextField txtNomSerConsulta;
    private javax.swing.JTextField txtPrecioServConsulta;
    // End of variables declaration//GEN-END:variables
}
