/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package VISTA;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;

/**
 *
 * @author danie
 */
public class Internalfrm_Servicios extends javax.swing.JInternalFrame {

    /**
     * Creates new form Internalfrm_Servicios
     */
    public Internalfrm_Servicios() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        boxNombreSer = new javax.swing.JComboBox<>();
        jPanel12 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblIdServicio = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblPrecioServicio = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        btnGuardarServicio = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        txtERROR = new javax.swing.JLabel();
        txtEXITO = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblIdCliente = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblIdServicio_Adm = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        boxHoraSerIN = new javax.swing.JComboBox<>();
        boxMinutosSerIN = new javax.swing.JComboBox<>();
        boxHoraSerFIN = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        boxMinutosSerFIN = new javax.swing.JComboBox<>();
        btnConsultar = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel5.setText("Nombre :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 50, 20));

        boxNombreSer.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        boxNombreSer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", " " }));
        jPanel1.add(boxNombreSer, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 330, 20));

        jPanel12.setBackground(new java.awt.Color(0, 153, 204));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, -1, 20));

        jPanel7.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, -1, 30));

        jPanel9.setBackground(new java.awt.Color(51, 153, 255));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 30, 30));

        jPanel10.setBackground(new java.awt.Color(0, 153, 204));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 40, 30));

        jPanel6.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 30, 40));

        jPanel11.setBackground(new java.awt.Color(0, 153, 204));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 40, -1));

        jPanel13.setBackground(new java.awt.Color(51, 153, 255));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel2.setText("Id servicio:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 60, 20));

        lblIdServicio.setFont(new java.awt.Font("Serif", 2, 12)); // NOI18N
        jPanel1.add(lblIdServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 150, 20));

        jLabel11.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel11.setText("Precio:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        lblPrecioServicio.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        lblPrecioServicio.setForeground(new java.awt.Color(0, 204, 51));
        lblPrecioServicio.setText("000 000");
        jPanel1.add(lblPrecioServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, -1));

        jPanel17.setBackground(new java.awt.Color(0, 153, 204));

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 40, -1));

        jPanel8.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, -1));

        jPanel15.setBackground(new java.awt.Color(51, 153, 255));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 30, 30));

        jPanel14.setBackground(new java.awt.Color(0, 153, 204));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, -1, -1));

        jPanel16.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 30, 30));

        jPanel18.setBackground(new java.awt.Color(51, 153, 255));

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, 10));

        btnGuardarServicio.setBackground(new java.awt.Color(0, 204, 102));
        btnGuardarServicio.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        btnGuardarServicio.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarServicio.setText("GUARDAR");
        btnGuardarServicio.setBorder(null);
        btnGuardarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarServicioActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardarServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, 90, 30));

        jLabel13.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 204, 51));
        jLabel13.setText("$");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        btnSalir.setBackground(new java.awt.Color(204, 204, 255));
        btnSalir.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("<");
        btnSalir.setBorder(null);
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 20, 20));

        txtERROR.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(txtERROR, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 260, 20));

        txtEXITO.setForeground(new java.awt.Color(51, 204, 0));
        jPanel1.add(txtEXITO, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 220, 20));

        jLabel3.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel3.setText("Id cliente:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 60, 20));

        lblIdCliente.setFont(new java.awt.Font("Serif", 2, 12)); // NOI18N
        jPanel1.add(lblIdCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 150, 20));

        jLabel6.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel6.setText("Id servicio admin:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 130, 20));

        lblIdServicio_Adm.setFont(new java.awt.Font("Serif", 2, 12)); // NOI18N
        jPanel1.add(lblIdServicio_Adm, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 130, 20));

        jLabel15.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Hora inicio");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 150, 20));

        boxHoraSerIN.setBackground(new java.awt.Color(235, 235, 235));
        boxHoraSerIN.setFont(new java.awt.Font("Segoe UI Symbol", 2, 12)); // NOI18N
        boxHoraSerIN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", " " }));
        boxHoraSerIN.setBorder(null);
        jPanel1.add(boxHoraSerIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 70, 20));

        boxMinutosSerIN.setBackground(new java.awt.Color(235, 235, 235));
        boxMinutosSerIN.setFont(new java.awt.Font("Segoe UI Symbol", 2, 12)); // NOI18N
        boxMinutosSerIN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", " " }));
        boxMinutosSerIN.setBorder(null);
        jPanel1.add(boxMinutosSerIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 80, 20));

        boxHoraSerFIN.setBackground(new java.awt.Color(235, 235, 235));
        boxHoraSerFIN.setFont(new java.awt.Font("Segoe UI Symbol", 2, 12)); // NOI18N
        boxHoraSerFIN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", " " }));
        boxHoraSerFIN.setBorder(null);
        jPanel1.add(boxHoraSerFIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 70, -1));

        jLabel12.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Hora fin");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 150, -1));

        boxMinutosSerFIN.setBackground(new java.awt.Color(235, 235, 235));
        boxMinutosSerFIN.setFont(new java.awt.Font("Segoe UI Symbol", 2, 12)); // NOI18N
        boxMinutosSerFIN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", " " }));
        boxMinutosSerFIN.setBorder(null);
        jPanel1.add(boxMinutosSerFIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 80, -1));

        btnConsultar.setBackground(new java.awt.Color(0, 153, 255));
        btnConsultar.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        btnConsultar.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultar.setText("CONSULTAR");
        btnConsultar.setBorder(null);
        jPanel1.add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 90, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarServicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarServicioActionPerformed

    public JButton getBtnConsultar() {
        return btnConsultar;
    }

    public void setBtnConsultar(JButton btnConsultar) {
        this.btnConsultar = btnConsultar;
    }

    public JComboBox<String> getBoxHoraSerFIN() {
        return boxHoraSerFIN;
    }

    public void setBoxHoraSerFIN(JComboBox<String> boxHoraSerFIN) {
        this.boxHoraSerFIN = boxHoraSerFIN;
    }

    public JComboBox<String> getBoxHoraSerIN() {
        return boxHoraSerIN;
    }

    public void setBoxHoraSerIN(JComboBox<String> boxHoraSerIN) {
        this.boxHoraSerIN = boxHoraSerIN;
    }

    public JComboBox<String> getBoxMinutosSerFIN() {
        return boxMinutosSerFIN;
    }

    public void setBoxMinutosSerFIN(JComboBox<String> boxMinutosSerFIN) {
        this.boxMinutosSerFIN = boxMinutosSerFIN;
    }

    public JComboBox<String> getBoxMinutosSerIN() {
        return boxMinutosSerIN;
    }

    public void setBoxMinutosSerIN(JComboBox<String> boxMinutosSerIN) {
        this.boxMinutosSerIN = boxMinutosSerIN;
    }

    public JComboBox<String> getBoxNombreSer() {
        return boxNombreSer;
    }

    public void setBoxNombreSer(JComboBox<String> boxNombreSer) {
        this.boxNombreSer = boxNombreSer;
    }

    public JButton getBtnGuardarServicio() {
        return btnGuardarServicio;
    }

    public void setBtnGuardarServicio(JButton btnGuardarServicio) {
        this.btnGuardarServicio = btnGuardarServicio;
    }

    public JButton getBtnSalir() {
        return btnSalir;
    }

    public void setBtnSalir(JButton btnSalir) {
        this.btnSalir = btnSalir;
    }

    public JLabel getLblIdCliente() {
        return lblIdCliente;
    }

    public void setLblIdCliente(JLabel lblIdCliente) {
        this.lblIdCliente = lblIdCliente;
    }

    public JLabel getLblIdServicio() {
        return lblIdServicio;
    }

    public void setLblIdServicio(JLabel lblIdServicio) {
        this.lblIdServicio = lblIdServicio;
    }

    public JLabel getLblIdServicio_Adm() {
        return lblIdServicio_Adm;
    }

    public void setLblIdServicio_Adm(JLabel lblIdServicio_Adm) {
        this.lblIdServicio_Adm = lblIdServicio_Adm;
    }

    public JLabel getLblPrecioServicio() {
        return lblPrecioServicio;
    }

    public void setLblPrecioServicio(JLabel lblPrecioServicio) {
        this.lblPrecioServicio = lblPrecioServicio;
    }

    public JLabel getTxtERROR() {
        return txtERROR;
    }

    public void setTxtERROR(JLabel txtERROR) {
        this.txtERROR = txtERROR;
    }

    public JLabel getTxtEXITO() {
        return txtEXITO;
    }

    public void setTxtEXITO(JLabel txtEXITO) {
        this.txtEXITO = txtEXITO;
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxHoraSerFIN;
    private javax.swing.JComboBox<String> boxHoraSerIN;
    private javax.swing.JComboBox<String> boxMinutosSerFIN;
    private javax.swing.JComboBox<String> boxMinutosSerIN;
    private javax.swing.JComboBox<String> boxNombreSer;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnGuardarServicio;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblIdCliente;
    private javax.swing.JLabel lblIdServicio;
    private javax.swing.JLabel lblIdServicio_Adm;
    private javax.swing.JLabel lblPrecioServicio;
    private javax.swing.JLabel txtERROR;
    private javax.swing.JLabel txtEXITO;
    // End of variables declaration//GEN-END:variables
}
