/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package VISTA;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;

/**
 *
 * @author danie
 */
public class Internalfrm_Hospedaje extends javax.swing.JInternalFrame {

    
    public JButton getBtnConsultar() {
        return btnConsultar;
    }

    public JLabel getLblIdReserva() {
        return lblIdReserva;
    }

    public void setLblIdReserva(JLabel lblIdReserva) {
        this.lblIdReserva = lblIdReserva;
    }

    /**
     * Creates new form Internalfrm_Hospedaje
     */
    public void setBtnConsultar(JButton btnConsultar) {    
        this.btnConsultar = btnConsultar;
    }

    public Internalfrm_Hospedaje() {
        initComponents();
    }

    public JButton getBtnSalir() {
        return btnSalir;
    }

    public void setBtnSalir(JButton btnSalir) {
        this.btnSalir = btnSalir;
    }

    public JLabel getLblERROR() {
        return lblERROR;
    }

    public JComboBox<String> getBoxAnioIng() {
        return BoxAnioIng;
    }

    public void setBoxAnioIng(JComboBox<String> BoxAnioIng) {
        this.BoxAnioIng = BoxAnioIng;
    }

    public JComboBox<String> getBoxAnioSal() {
        return BoxAnioSal;
    }

    public void setBoxAnioSal(JComboBox<String> BoxAnioSal) {
        this.BoxAnioSal = BoxAnioSal;
    }

    public JComboBox<String> getBoxDiaIng() {
        return BoxDiaIng;
    }

    public void setBoxDiaIng(JComboBox<String> BoxDiaIng) {
        this.BoxDiaIng = BoxDiaIng;
    }

    public JComboBox<String> getBoxDiaSal() {
        return BoxDiaSal;
    }

    public void setBoxDiaSal(JComboBox<String> BoxDiaSal) {
        this.BoxDiaSal = BoxDiaSal;
    }

    public JComboBox<String> getBoxMesIng() {
        return BoxMesIng;
    }

    public void setBoxMesIng(JComboBox<String> BoxMesIng) {
        this.BoxMesIng = BoxMesIng;
    }

    public JComboBox<String> getBoxMesSal() {
        return BoxMesSal;
    }

    public void setBoxMesSal(JComboBox<String> BoxMesSal) {
        this.BoxMesSal = BoxMesSal;
    }

    public JComboBox<String> getBoxHoraIng() {
        return boxHoraIng;
    }

    public void setBoxHoraIng(JComboBox<String> boxHoraIng) {
        this.boxHoraIng = boxHoraIng;
    }

    public JComboBox<String> getBoxHoraSal() {
        return boxHoraSal;
    }

    public void setBoxHoraSal(JComboBox<String> boxHoraSal) {
        this.boxHoraSal = boxHoraSal;
    }

    public JComboBox<String> getBoxMinIng() {
        return boxMinIng;
    }

    public void setBoxMinIng(JComboBox<String> boxMinIng) {
        this.boxMinIng = boxMinIng;
    }

    public JComboBox<String> getBoxMinSal() {
        return boxMinSal;
    }

    public void setBoxMinSal(JComboBox<String> boxMinSal) {
        this.boxMinSal = boxMinSal;
    }

    public JComboBox<String> getBoxTipoHab() {
        return boxTipoHab;
    }

    public void setBoxTipoHab(JComboBox<String> boxTipoHab) {
        this.boxTipoHab = boxTipoHab;
    }

    public JButton getBtnGuardarHos() {
        return btnGuardarHos;
    }

    public void setBtnGuardarHos(JButton btnGuardarHos) {
        this.btnGuardarHos = btnGuardarHos;
    }

    public JLabel getLblIdHabitacion() {
        return lblIdHabitacion;
    }

    public void setLblIdHabitacion(JLabel lblIdHabitacion) {
        this.lblIdHabitacion = lblIdHabitacion;
    }

    public JLabel getLblIdHosp() {
        return lblIdHosp;
    }

    public void setLblIdHosp(JLabel lblIdHosp) {
        this.lblIdHosp = lblIdHosp;
    }

    public JLabel getLblPrecio() {
        return lblPrecio;
    }

    public void setLblPrecio(JLabel lblPrecio) {
        this.lblPrecio = lblPrecio;
    }

    public void setLblERROR(JLabel lblERROR) {
        this.lblERROR = lblERROR;
    }

    public JLabel getLblEXITO() {
        return lblEXITO;
    }

    public void setLblEXITO(JLabel lblEXITO) {
        this.lblEXITO = lblEXITO;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel30 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jPanel28 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        jPanel29 = new javax.swing.JPanel();
        BoxAnioSal = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        BoxMesSal = new javax.swing.JComboBox<>();
        BoxDiaSal = new javax.swing.JComboBox<>();
        BoxAnioIng = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        BoxMesIng = new javax.swing.JComboBox<>();
        BoxDiaIng = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        boxTipoHab = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        boxHoraIng = new javax.swing.JComboBox<>();
        boxMinIng = new javax.swing.JComboBox<>();
        boxHoraSal = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        boxMinSal = new javax.swing.JComboBox<>();
        btnGuardarHos = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblIdHosp = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblPrecio$ = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        lblPrecio = new javax.swing.JLabel();
        lblEXITO = new javax.swing.JLabel();
        lblERROR = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        lblIdHabitacion = new javax.swing.JLabel();
        btnConsultar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        lblIdReserva = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, -1, -1));

        jPanel30.setBackground(new java.awt.Color(102, 204, 255));

        javax.swing.GroupLayout jPanel30Layout = new javax.swing.GroupLayout(jPanel30);
        jPanel30.setLayout(jPanel30Layout);
        jPanel30Layout.setHorizontalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel30Layout.setVerticalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, -1, 20));

        jPanel26.setBackground(new java.awt.Color(102, 204, 255));

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, -1, 20));

        jPanel28.setBackground(new java.awt.Color(51, 102, 255));

        javax.swing.GroupLayout jPanel28Layout = new javax.swing.GroupLayout(jPanel28);
        jPanel28.setLayout(jPanel28Layout);
        jPanel28Layout.setHorizontalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jPanel28Layout.setVerticalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 70, 20));

        jPanel25.setBackground(new java.awt.Color(0, 102, 204));

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 50, 30));

        jPanel10.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, -1, -1));

        jPanel24.setBackground(new java.awt.Color(102, 204, 255));

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, -1, -1));

        jPanel23.setBackground(new java.awt.Color(51, 102, 255));

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, -1, -1));

        jPanel27.setBackground(new java.awt.Color(0, 102, 204));

        javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel27Layout.setVerticalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 40, 40));

        jPanel29.setBackground(new java.awt.Color(51, 102, 255));

        javax.swing.GroupLayout jPanel29Layout = new javax.swing.GroupLayout(jPanel29);
        jPanel29.setLayout(jPanel29Layout);
        jPanel29Layout.setHorizontalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );
        jPanel29Layout.setVerticalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, -1, -1));

        BoxAnioSal.setBackground(new java.awt.Color(235, 235, 235));
        BoxAnioSal.setFont(new java.awt.Font("Segoe UI Symbol", 2, 12)); // NOI18N
        BoxAnioSal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Año", "2022", "2023" }));
        BoxAnioSal.setBorder(null);
        jPanel2.add(BoxAnioSal, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel3.setText("Fecha de salida del hospedaje:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, -1, -1));

        BoxMesSal.setBackground(new java.awt.Color(235, 235, 235));
        BoxMesSal.setFont(new java.awt.Font("Segoe UI Symbol", 2, 12)); // NOI18N
        BoxMesSal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mes", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        BoxMesSal.setBorder(null);
        jPanel2.add(BoxMesSal, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, -1, -1));

        BoxDiaSal.setBackground(new java.awt.Color(235, 235, 235));
        BoxDiaSal.setFont(new java.awt.Font("Segoe UI Symbol", 2, 12)); // NOI18N
        BoxDiaSal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Día", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        BoxDiaSal.setBorder(null);
        BoxDiaSal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxDiaSalActionPerformed(evt);
            }
        });
        jPanel2.add(BoxDiaSal, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 60, -1));

        BoxAnioIng.setBackground(new java.awt.Color(235, 235, 235));
        BoxAnioIng.setFont(new java.awt.Font("Segoe UI Symbol", 2, 12)); // NOI18N
        BoxAnioIng.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Año", "2022" }));
        BoxAnioIng.setBorder(null);
        jPanel2.add(BoxAnioIng, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, -1));

        jLabel7.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel7.setText("Fecha de ingreso al hospedaje:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        BoxMesIng.setBackground(new java.awt.Color(235, 235, 235));
        BoxMesIng.setFont(new java.awt.Font("Segoe UI Symbol", 2, 12)); // NOI18N
        BoxMesIng.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mes", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        BoxMesIng.setBorder(null);
        jPanel2.add(BoxMesIng, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        BoxDiaIng.setBackground(new java.awt.Color(235, 235, 235));
        BoxDiaIng.setFont(new java.awt.Font("Segoe UI Symbol", 2, 12)); // NOI18N
        BoxDiaIng.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Día", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        BoxDiaIng.setBorder(null);
        BoxDiaIng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxDiaIngActionPerformed(evt);
            }
        });
        jPanel2.add(BoxDiaIng, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 60, -1));

        jLabel4.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel4.setText("Tipo habitación:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        boxTipoHab.setBackground(new java.awt.Color(235, 235, 235));
        boxTipoHab.setFont(new java.awt.Font("Segoe UI Symbol", 2, 12)); // NOI18N
        boxTipoHab.setBorder(null);
        boxTipoHab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxTipoHabActionPerformed(evt);
            }
        });
        jPanel2.add(boxTipoHab, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 430, -1));

        jLabel6.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel6.setText("Hora de ingreso al hospedaje:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 160, -1));

        boxHoraIng.setBackground(new java.awt.Color(235, 235, 235));
        boxHoraIng.setFont(new java.awt.Font("Segoe UI Symbol", 2, 12)); // NOI18N
        boxHoraIng.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hora", "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));
        boxHoraIng.setBorder(null);
        jPanel2.add(boxHoraIng, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        boxMinIng.setBackground(new java.awt.Color(235, 235, 235));
        boxMinIng.setFont(new java.awt.Font("Segoe UI Symbol", 2, 12)); // NOI18N
        boxMinIng.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Minutos", "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
        boxMinIng.setBorder(null);
        jPanel2.add(boxMinIng, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, -1));

        boxHoraSal.setBackground(new java.awt.Color(235, 235, 235));
        boxHoraSal.setFont(new java.awt.Font("Segoe UI Symbol", 2, 12)); // NOI18N
        boxHoraSal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hora", "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));
        boxHoraSal.setBorder(null);
        jPanel2.add(boxHoraSal, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel5.setText("Hora de salida del hospedaje:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, -1, -1));

        boxMinSal.setBackground(new java.awt.Color(235, 235, 235));
        boxMinSal.setFont(new java.awt.Font("Segoe UI Symbol", 2, 12)); // NOI18N
        boxMinSal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Minutos", "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
        boxMinSal.setBorder(null);
        jPanel2.add(boxMinSal, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, -1, -1));

        btnGuardarHos.setBackground(new java.awt.Color(0, 204, 102));
        btnGuardarHos.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        btnGuardarHos.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarHos.setText("GUARDAR");
        btnGuardarHos.setBorder(null);
        jPanel2.add(btnGuardarHos, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 110, 30));

        jLabel2.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel2.setText("Id hospedaje:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        lblIdHosp.setFont(new java.awt.Font("Serif", 2, 12)); // NOI18N
        jPanel2.add(lblIdHosp, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 110, 20));

        jLabel8.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel8.setText("Precio:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, -1, -1));

        lblPrecio$.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        lblPrecio$.setForeground(new java.awt.Color(0, 204, 51));
        lblPrecio$.setText("$");
        jPanel2.add(lblPrecio$, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, -1, -1));

        jPanel22.setBackground(new java.awt.Color(51, 102, 255));

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, -1, 10));

        jPanel16.setBackground(new java.awt.Color(0, 153, 204));

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 50, 20));

        jPanel20.setBackground(new java.awt.Color(0, 102, 204));

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 50, 30));

        jPanel17.setBackground(new java.awt.Color(102, 204, 255));

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 30, 30));

        jPanel15.setBackground(new java.awt.Color(51, 102, 255));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 50, 30));

        jPanel8.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 50, 30));

        lblPrecio.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        lblPrecio.setForeground(new java.awt.Color(0, 204, 51));
        lblPrecio.setText("000 000");
        jPanel2.add(lblPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, -1, -1));

        lblEXITO.setForeground(new java.awt.Color(0, 204, 0));
        jPanel2.add(lblEXITO, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 120, 20));

        lblERROR.setForeground(new java.awt.Color(255, 0, 0));
        jPanel2.add(lblERROR, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 300, 20));

        btnSalir.setBackground(new java.awt.Color(204, 204, 255));
        btnSalir.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("<");
        btnSalir.setBorder(null);
        jPanel2.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 20, 20));

        jLabel9.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel9.setText("Id habitacion:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        lblIdHabitacion.setFont(new java.awt.Font("Serif", 2, 12)); // NOI18N
        jPanel2.add(lblIdHabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 110, 20));

        btnConsultar.setBackground(new java.awt.Color(0, 153, 255));
        btnConsultar.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        btnConsultar.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultar.setText("CONSULTAR");
        btnConsultar.setBorder(null);
        jPanel2.add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 90, 30));

        jLabel10.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel10.setText("Id reserva:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        lblIdReserva.setFont(new java.awt.Font("Serif", 2, 12)); // NOI18N
        jPanel2.add(lblIdReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 120, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BoxDiaSalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxDiaSalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxDiaSalActionPerformed

    private void BoxDiaIngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxDiaIngActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxDiaIngActionPerformed

    private void boxTipoHabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxTipoHabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxTipoHabActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BoxAnioIng;
    private javax.swing.JComboBox<String> BoxAnioSal;
    private javax.swing.JComboBox<String> BoxDiaIng;
    private javax.swing.JComboBox<String> BoxDiaSal;
    private javax.swing.JComboBox<String> BoxMesIng;
    private javax.swing.JComboBox<String> BoxMesSal;
    private javax.swing.JComboBox<String> boxHoraIng;
    private javax.swing.JComboBox<String> boxHoraSal;
    private javax.swing.JComboBox<String> boxMinIng;
    private javax.swing.JComboBox<String> boxMinSal;
    private javax.swing.JComboBox<String> boxTipoHab;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnGuardarHos;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel lblERROR;
    private javax.swing.JLabel lblEXITO;
    private javax.swing.JLabel lblIdHabitacion;
    private javax.swing.JLabel lblIdHosp;
    private javax.swing.JLabel lblIdReserva;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblPrecio$;
    // End of variables declaration//GEN-END:variables
}
